// ============================================================================
// 🌍 ExamDisciplineHintsBootstrap — AI-translated Exam discipline hints
// for the 14 Tier-1/2 bootstrap languages.
//
// Generated by `tool/bootstrap_exam_discipline_hints.dart` on 2026-05-14T12:05:01.420290.
// Source-of-truth: IT cells in `discipline_hints_exam_it.dart`. Model: gemini-2.5-flash.
//
// Status: `ai_bootstrap` per docs/socratic_native_validation_protocol.md.
// ============================================================================

import '../../../canvas/ai/socratic/socratic_discipline.dart';

const Map<String, Map<Discipline, String>> _bootstrapExamDisciplineHints = {
  'es': {
    Discipline.physics: '''DISCIPLINA: física.
Verbos Bloom-Apply: calcula (fuerza neta, momento, energía), predice (trayectoria, posición t+Δt), aplica (Newton II, conservación).
Verbos Bloom-Analyze: deriva (ecuación del movimiento), distingue (elástico/inelástico), compara (sistemas inerciales vs no inerciales).
Verbos Bloom-Evaluate: evalúa la estabilidad de un sistema, critica una hipótesis de modelo.
Escenarios preferidos: plano inclinado con fricción, choques 1D/2D, oscilador armónico, circuitos RLC, termodinámica del ciclo de Carnot.''',
    Discipline.math: '''DISCIPLINA: matemáticas.
Verbos Bloom-Apply: resuelve (ecuación, sistema), calcula (límite, derivada, integral por partes/sustitución), aplica (regla de l'Hôpital, teorema de Lagrange).
Verbos Bloom-Analyze: demuestra (por inducción, por reducción al absurdo, contrapositivo), encuentra un contraejemplo, muestra la equivalencia, clasifica las discontinuidades.
Verbos Bloom-Evaluate: critica una demostración, evalúa la generalidad de un teorema.
Nunca solo "calcula" como único verbo — la matemática de examen es una prueba.''',
    Discipline.chemistry: '''DISCIPLINA: química.
Verbos Bloom-Apply: equilibra (reacción redox, neutralización), calcula (molaridad, pH, concentración), predice (producto de reacción).
Verbos Bloom-Analyze: distingue (ácido fuerte/débil, SN1/SN2), explica el mecanismo molecular, clasifica los compuestos por grupo funcional.
Verbos Bloom-Evaluate: evalúa la espontaneidad termodinámica (ΔG), critica una ruta de síntesis.
Busca SIEMPRE la causalidad molecular y el nivel de representación (molecular/macroscópico/simbólico).''',
    Discipline.biology: '''DISCIPLINA: biología.
Verbos Bloom-Apply: aplica (Hardy-Weinberg, leyes de Mendel), predice (fenotipos F2, resultado de mutación), calcula (frecuencias alélicas).
Verbos Bloom-Analyze: distingue (mitosis/meiosis, procariotas/eucariotas), explica la función (orgánulo, sistema), compara (selección natural vs. deriva genética).
Verbos Bloom-Evaluate: evalúa la evidencia de una hipótesis evolutiva, critica un modelo experimental.
Ejemplos: ATP-sintasa, regulación génica, homeostasis, ecosistemas.''',
    Discipline.medicine: '''DISCIPLINA: medicina.
Verbos Bloom-Apply: diagnostica (basándose en síntomas/signos), propón (terapia de primera línea), aplica (criterios DSM, guías ESC).
Verbos Bloom-Analyze: distingue (diagnóstico diferencial), interpreta (pruebas de laboratorio, imagenología), evalúa la fisiopatología subyacente.
Verbos Bloom-Evaluate: critica un tratamiento, evalúa el pronóstico, razona sobre la evidencia (RCT vs informe de caso).
Escenarios clínicos concretos con anamnesis + pruebas + pronóstico esperado.''',
    Discipline.law: '''DISCIPLINA: derecho.
Verbos Bloom-Apply: aplica (norma al caso concreto), califica (supuesto de hecho), identifica (responsabilidad).
Verbos Bloom-Analyze: distingue (dolo/culpa, contrato/acto unilateral), compara (precedentes jurisprudenciales), argumenta de la ratio legis.
Verbos Bloom-Evaluate: evalúa la legitimidad de un acto, critica una interpretación jurisprudencial.
Escenarios preferidos: casos concretos con elementos del supuesto de hecho claros + normas aplicables (código civil, penal, constitución).''',
    Discipline.economics: '''DISCIPLINA: economía.
Verbos Bloom-Apply: calcula (elasticidad, PIB, excedente), aplica (modelo de competencia perfecta, IS-LM), predice el efecto de una política monetaria/fiscal.
Verbos Bloom-Analyze: distingue (efecto sustitución vs. renta), compara (regímenes de mercado), interpreta datos macroeconómicos.
Verbos Bloom-Evaluate: evalúa una política económica, critica un supuesto de un modelo (movilidad perfecta, racionalidad).
Ejemplos con gráficos de oferta y demanda + datos numéricos realistas.''',
    Discipline.philosophy: '''DISCIPLINA: filosofía.
Verbos Bloom-Apply: aplica (categoría kantiana a un caso, principio utilitarista), clasifica (filósofo por corriente, texto por escuela).
Verbos Bloom-Analyze: compara (Platón vs Aristóteles, Hume vs Kant), distingue (ética deontológica vs consecuencialista), argumenta desde la fuente.
Verbos Bloom-Evaluate: critica una tesis, evalúa la coherencia interna de un sistema, construye una contraargumentación.
Ejemplos: dilema del tranvía, paradoja del mentiroso, problema mente-cuerpo.''',
    Discipline.history: '''DISCIPLINA: historia.
Verbos Bloom-Apply: asigna correctamente una fecha a un evento, aplica (categoría periodizadora a un hecho), localiza (causa próxima vs. causa remota).
Verbos Bloom-Analyze: distingue (causas económicas/políticas/sociales), compara (Revolución francesa vs. americana), interpreta una fuente primaria, identifica sesgos.
Verbos Bloom-Evaluate: evalúa el impacto de un evento, critica una tesis historiográfica, argumenta a partir de la evidencia documental.
Evita fechas estériles: pregunta POR QUÉ + CÓMO, no solo CUÁNDO.''',
    Discipline.generic: '''DISCIPLINA: genérica.
Verbos Bloom-Apply: aplica, calcula, predice, clasifica.
Verbos Bloom-Analyze: distingue, compara, interpreta, deriva.
Verbos Bloom-Evaluate: evalúa, critica, argumenta, justifica.
Sin dominio específico, privilegia preguntas que requieran razonamiento multi-paso y que sean resolubles a partir de los apuntes del clúster.
Evita preguntas genéricas tipo "¿Qué es X?" (Remember-only).''',
  },
  'pt': {
    Discipline.physics: '''DISCIPLINA: física.
Verbos Bloom-Apply: calcula (força resultante, momento, energia), prevê (trajetória, posição t+Δt), aplica (Newton II, conservação).
Verbos Bloom-Analyze: deriva (equação do movimento), distingue (elástico/inelástico), compara (sistemas inerciais vs não-inerciais).
Verbos Bloom-Evaluate: avalia a estabilidade de um sistema, critica uma hipótese de modelo.
Cenários preferidos: plano inclinado com atrito, colisões 1D/2D, oscilador harmônico, circuitos RLC, termodinâmica do ciclo de Carnot.''',
    Discipline.math: '''DISCIPLINA: matemática.
Verbos Bloom-Apply: resolve (equação, sistema), calcula (limite, derivada, integral por partes/substituição), aplica (regra de de l'Hôpital, teorema de Lagrange).
Verbos Bloom-Analyze: demonstra (por indução, por absurdo, contrapositivo), encontra um contraexemplo, mostra a equivalência, classifica as descontinuidades.
Verbos Bloom-Evaluate: critica uma demonstração, avalia a generalidade de um teorema.
Nunca apenas "calcula" como único verbo — a matemática de exame é uma prova.''',
    Discipline.chemistry: '''DISCIPLINA: química.
Verbos Bloom-Apply: equilibra (reação redox, neutralização), calcula
(molaridade, pH, concentração), prevê (produto de reação).
Verbos Bloom-Analyze: distingue (ácido forte/fraco, SN1/SN2), explica
o mecanismo molecular, classifica os compostos por grupo funcional.
Verbos Bloom-Evaluate: avalia a espontaneidade termodinâmica (ΔG),
critica uma via de síntese.
Busca SEMPRE a causalidade molecular e o nível de representação
(molecular/macroscópico/simbólico).''',
    Discipline.biology: '''DISCIPLINA: biologia.
Verbos Bloom-Apply: aplica (Hardy-Weinberg, leis de Mendel), prevê (fenótipos F2, resultado de mutação), calcula (frequências alélicas).
Verbos Bloom-Analyze: distingue (mitose/meiose, procariotos/eucariotos), explica a função (organela, sistema), compara (seleção natural vs. deriva genética).
Verbos Bloom-Evaluate: avalia a evidência de uma hipótese evolutiva, critica um modelo experimental.
Exemplos: ATP-sintase, regulação gênica, homeostase, ecossistemas.''',
    Discipline.medicine: '''DISCIPLINA: medicina.
Verbos Bloom-Apply: diagnostica (com base em sintomas/sinais), propõe (terapia de primeira linha), aplica (critérios DSM, diretrizes ESC).
Verbos Bloom-Analyze: distingue (diagnóstico diferencial), interpreta (exames laboratoriais, exames de imagem), avalia a fisiopatologia subjacente.
Verbos Bloom-Evaluate: critica um tratamento, avalia o prognóstico, raciocina sobre a evidência (RCT vs case report).
Cenários clínicos concretos com anamnese + exames + prognóstico esperado.''',
    Discipline.law: '''DISCIPLINA: direito.
Verbos Bloom-Apply: aplica (norma ao caso concreto), qualifica
(fato jurídico), identifica (responsabilidade).
Verbos Bloom-Analyze: distingue (dolo/culpa, contrato/ato unilateral),
compara (precedentes jurisprudenciais), argumenta a partir da ratio legis.
Verbos Bloom-Evaluate: avalia a legitimidade de um ato, critica
uma interpretação jurisprudencial.
Cenários preferidos: casos concretos com elementos de fato jurídico claros +
normas aplicáveis (código civil, penal, constituição).''',
    Discipline.economics: '''DISCIPLINA: economia.
Verbos Bloom-Apply: calcula (elasticidade, PIB, excedente), aplica (modelo de concorrência perfeita, IS-LM), prevê o efeito de uma política monetária/fiscal.
Verbos Bloom-Analyze: distingue (efeito substituição vs. renda), compara (regimes de mercado), interpreta dados macroeconômicos.
Verbos Bloom-Evaluate: avalia uma política econômica, critica um pressuposto de um modelo (mobilidade perfeita, racionalidade).
Exemplos com gráficos demanda-oferta + dados numéricos realistas.''',
    Discipline.philosophy: '''DISCIPLINA: filosofia.
Verbos Bloom-Apply: aplica (categoria kantiana a um caso, princípio
utilitarista), classifica (filósofo por corrente, texto por escola).
Verbos Bloom-Analyze: compara (Platão vs Aristóteles, Hume vs Kant),
distingue (ética deontológica vs consequencialista), argumenta a partir da
fonte.
Verbos Bloom-Evaluate: critica uma tese, avalia a coerência interna
de um sistema, constrói uma contra-argumentação.
Exemplos: dilema do bonde, paradoxo do mentiroso, problema mente-corpo.''',
    Discipline.history: '''DISCIPLINA: história.
Verbos Bloom-Apply: dado corretamente um evento, aplica (categoria periodizante a um fato), localiza (causa próxima vs causa remota).
Verbos Bloom-Analyze: distingue (causas econômicas/políticas/sociais), compara (Revolução Francesa vs Americana), interpreta uma fonte primária, identifica vieses.
Verbos Bloom-Evaluate: avalia o impacto de um evento, critica uma tese historiográfica, argumenta com base em evidência documental.
Evita datas estéreis: pergunta POR QUE + COMO, não apenas QUANDO.''',
    Discipline.generic: '''DISCIPLINA: genérica.
Verbos Bloom-Apply: aplica, calcula, prevê, classifica.
Verbos Bloom-Analyze: distingue, compara, interpreta, deriva.
Verbos Bloom-Evaluate: avalia, critica, argumenta, justifica.
Sem domínio específico, privilegia perguntas que exijam raciocínio de múltiplas etapas e que sejam solucionáveis pelos apontamentos do cluster.
Evita perguntas genéricas do tipo "O que é X?" (Remember-only).''',
  },
  'fr': {
    Discipline.physics: '''DISCIPLINE: physique.
Verbes Bloom-Apply: calcule (force nette, moment, énergie), prédis (trajectoire, position à t+Δt), applique (Newton II, conservation).
Verbes Bloom-Analyze: dérive (équation du mouvement), distingue (élastique/inélastique), compare (systèmes inertiels vs non-inertiels).
Verbes Bloom-Evaluate: évalue la stabilité d'un système, critique une hypothèse de modèle.
Scénarios préférés: plan incliné avec frottement, collisions 1D/2D, oscillateur harmonique, circuits RLC, thermodynamique du cycle de Carnot.''',
    Discipline.math: '''DISCIPLINE: mathématiques.
Verbes Bloom-Apply: résous (équation, système), calcule (limite,
dérivée, intégrale par parties/substitution), applique (règle de
l'Hôpital, théorème de Lagrange).
Verbes Bloom-Analyze: démontre (par récurrence, par l'absurde, par contraposition),
trouve un contre-exemple, montre l'équivalence, classe les discontinuités.
Verbes Bloom-Evaluate: critique une démonstration, évalue la généralité
d'un théorème.
Jamais seulement "calcule" comme unique verbe — les mathématiques d'examen sont une preuve.''',
    Discipline.chemistry: '''DISCIPLINE: chimie.
Verbes Bloom-Apply: équilibre (réaction redox, neutralisation), calcule (molarité, pH, concentration), prédis (produit de réaction).
Verbes Bloom-Analyze: distingue (acide fort/faible, SN1/SN2), explique le mécanisme moléculaire, classe les composés par groupe fonctionnel.
Verbes Bloom-Evaluate: évalue la spontanéité thermodynamique (ΔG), critique une voie de synthèse.
Recherche TOUJOURS la causalité moléculaire et le niveau de représentation (moléculaire/macroscopique/symbolique).''',
    Discipline.biology: '''DISCIPLINE: biologie.
Verbes Bloom-Apply: applique (Hardy-Weinberg, lois de Mendel), prédis (phénotypes F2, issue d'une mutation), calcule (fréquences alléliques).
Verbes Bloom-Analyze: distingue (mitose/méiose, procaryotes/eucaryotes), explique la fonction de (un organite, un système), compare (sélection naturelle vs dérive génétique).
Verbes Bloom-Evaluate: évalue les preuves d'une hypothèse évolutive, critique un modèle expérimental.
Exemples: ATP-synthase, régulation génique, homéostasie, écosystèmes.''',
    Discipline.medicine: '''DISCIPLINE: médecine.
Verbes Bloom-Apply: diagnostique (sur la base de symptômes/signes), propose
(un traitement de première intention), applique (les critères DSM, les lignes directrices ESC).
Verbes Bloom-Analyze: distingue (un diagnostic différentiel), interprète
(les examens de laboratoire, l'imagerie), évalue la physiopathologie sous-jacente.
Verbes Bloom-Evaluate: critique un traitement, évalue le pronostic,
raisonne sur les preuves (RCT vs rapport de cas).
Scénarios cliniques concrets avec anamnèse + examens + pronostic attendu.''',
    Discipline.law: '''DISCIPLINE: droit.
Verbes Bloom-Apply: appliquer (une norme à un cas concret), qualifier (une situation juridique), identifier (une responsabilité).
Verbes Bloom-Analyze: distinguer (dol/faute, contrat/acte unilatéral), comparer (des précédents jurisprudentiels), argumenter à partir de la ratio legis.
Verbes Bloom-Evaluate: évaluer la légitimité d'un acte, critiquer une interprétation jurisprudentielle.
Scénarios préférés: cas concrets avec des éléments de qualification clairs + normes applicables (code civil, pénal, constitution).''',
    Discipline.economics: '''DISCIPLINE: économie.
Verbes Bloom-Apply: calcule (élasticité, PIB, surplus), applique (modèle de concurrence parfaite, IS-LM), prédis l'effet d'une politique monétaire/fiscale.
Verbes Bloom-Analyze: distingue (effet de substitution vs revenu), compare (régimes de marché), interprète des données macroéconomiques.
Verbes Bloom-Evaluate: évalue une politique économique, critique une hypothèse de modèle (mobilité parfaite, rationalité).
Exemples avec graphiques offre-demande + données numériques réalistes.''',
    Discipline.philosophy: '''DISCIPLINE: philosophie.
Verbes Bloom-Apply: applique (une catégorie kantienne à un cas, un principe utilitariste), classe (un philosophe par courant, un texte par école).
Verbes Bloom-Analyze: compare (Platon vs Aristote, Hume vs Kant), distingue (éthique déontologique vs conséquentialiste), argumente à partir de la source.
Verbes Bloom-Evaluate: critique une thèse, évalue la cohérence interne d'un système, construis une contre-argumentation.
Exemples: dilemme du tramway, paradoxe du menteur, problème corps-esprit.''',
    Discipline.history: '''DISCIPLINE: histoire.
Verbes Bloom-Apply: situer correctement un événement, appliquer (une catégorie de périodisation à un fait), localiser (cause prochaine vs cause lointaine).
Verbes Bloom-Analyze: distinguer (causes économiques/politiques/sociales), comparer (Révolution française vs américaine), interpréter une source primaire, identifier les biais.
Verbes Bloom-Evaluate: évaluer l'impact d'un événement, critiquer une thèse historiographique, argumenter à partir de preuves documentaires.
Éviter les dates stériles : demander POURQUOI + COMMENT, pas seulement QUAND.''',
    Discipline.generic: '''DISCIPLINE: générique.
Verbes Bloom-Apply: applique, calcule, prédis, classe.
Verbes Bloom-Analyze: distingue, compare, interprète, déduis.
Verbes Bloom-Evaluate: évalue, critique, argumente, justifie.
Sans domaine spécifique, privilégie les questions qui nécessitent un raisonnement en plusieurs étapes et qui sont résolvables à partir des notes du cluster.
Évite les questions génériques du type "Qu'est-ce que X ?" (Remember-only).''',
  },
  'de': {
    Discipline.physics: '''FACHGEBIET: Physik.
Verben Bloom-Apply: berechne (Nettokraft, Moment, Energie), sage voraus (Flugbahn, Position zum Zeitpunkt t+Δt), wende an (zweites Newtonsches Gesetz, Erhaltungssätze).
Verben Bloom-Analyze: leite ab (Bewegungsgleichung), unterscheide (elastisch/inelastisch), vergleiche (Inertialsysteme vs. Nicht-Inertialsysteme).
Verben Bloom-Evaluate: bewerte die Stabilität eines Systems, kritisiere eine Modellhypothese.
Bevorzugte Szenarien: schiefe Ebene mit Reibung, Stöße 1D/2D, harmonischer Oszillator, RLC-Schaltkreise, Thermodynamik des Carnot-Kreisprozesses.''',
    Discipline.math: '''DISZIPLIN: Mathematik.
Verben Bloom-Apply: löse (Gleichung, System), berechne (Grenzwert, Ableitung, Integral mittels partieller Integration/Substitution), wende an (Regel von de l'Hôpital, Satz von Lagrange).
Verben Bloom-Analyze: beweise (durch Induktion, durch Widerspruch, durch Kontraposition), finde ein Gegenbeispiel, zeige die Äquivalenz, klassifiziere die Unstetigkeiten.
Verben Bloom-Evaluate: kritisiere einen Beweis, bewerte die Allgemeingültigkeit eines Theorems.
Niemals nur "berechne" als einziges Verb – die Prüfungsmathematik ist ein Nachweis.''',
    Discipline.chemistry: '''DISZIPLIN: Chemie.
Verben Bloom-Apply: bilanziere (Redoxreaktion, Neutralisation), berechne (Molarität, pH-Wert, Konzentration), sage voraus (Reaktionsprodukt).
Verben Bloom-Analyze: unterscheide (starke/schwache Säure, SN1/SN2), erkläre den molekularen Mechanismus, klassifiziere Verbindungen nach funktioneller Gruppe.
Verben Bloom-Evaluate: bewerte die thermodynamische Spontaneität (ΔG), kritisiere einen Syntheseweg.
Suche IMMER nach der molekularen Kausalität und dem Darstellungsniveau (molekular/makroskopisch/symbolisch).''',
    Discipline.biology: '''DISZIPLIN: Biologie.
Verben Bloom-Apply: anwenden (Hardy-Weinberg, Mendelsche Regeln), vorhersagen (F2-Phänotypen, Mutationsergebnis), berechnen (Allelhäufigkeiten).
Verben Bloom-Analyze: unterscheiden (Mitose/Meiose, Prokaryoten/Eukaryoten), die Funktion erklären (Organell, System), vergleichen (natürliche Selektion vs. Gendrift).
Verben Bloom-Evaluate: die Evidenz einer evolutionären Hypothese bewerten, ein experimentelles Modell kritisieren.
Beispiele: ATP-Synthase, Genregulation, Homöostase, Ökosysteme.''',
    Discipline.medicine: '''FACHGEBIET: Medizin.
Verben Bloom-Apply: diagnostiziere (basierend auf Symptomen/Anzeichen), empfehle (Erstlinientherapie), wende an (DSM-Kriterien, ESC-Leitlinien).
Verben Bloom-Analyze: unterscheide (Differentialdiagnose), interpretiere (Laboruntersuchungen, Bildgebung), bewerte die zugrunde liegende Pathophysiologie.
Verben Bloom-Evaluate: kritisiere eine Behandlung, bewerte die Prognose, begründe mit Evidenz (RCT vs. Fallbericht).
Konkrete klinische Szenarien mit Anamnese + Untersuchungen + erwarteter Prognose.''',
    Discipline.law: '''FACHGEBIET: Recht.
Verben Bloom-Apply: anwenden (Norm auf konkreten Fall), rechtlich einordnen
(Sachverhalt), feststellen (Verantwortlichkeit).
Verben Bloom-Analyze: unterscheiden (Vorsatz/Fahrlässigkeit, Vertrag/einseitiges
Rechtsgeschäft), vergleichen (Rechtsprechung), aus der ratio legis argumentieren.
Verben Bloom-Evaluate: beurteilen (Rechtmäßigkeit eines Aktes), kritisieren
(gerichtliche Auslegung).
Bevorzugte Szenarien: konkrete Fälle mit klaren Sachverhaltselementen +
anwendbare Normen (Bürgerliches Gesetzbuch, Strafgesetzbuch, Verfassung).''',
    Discipline.economics: '''FACHGEBIET: Volkswirtschaftslehre.
Verben Bloom-Apply: berechne (Elastizität, BIP, Überschuss), wende an (Modell des vollkommenen Wettbewerbs, IS-LM), sage die Auswirkung einer Geld-/Fiskalpolitik voraus.
Verben Bloom-Analyze: unterscheide (Substitutions- und Einkommenseffekt), vergleiche (Marktformen), interpretiere makroökonomische Daten.
Verben Bloom-Evaluate: bewerte eine Wirtschaftspolitik, kritisiere eine Annahme eines Modells (vollkommene Mobilität, Rationalität).
Beispiele mit Angebots-Nachfrage-Diagrammen + realistischen numerischen Daten.''',
    Discipline.philosophy: '''DISZIPLIN: Philosophie.
Verben Bloom-Apply: anwenden (eine kantianische Kategorie auf einen Fall, ein utilitaristisches Prinzip), klassifizieren (Philosophen nach Strömung, Text nach Schule).
Verben Bloom-Analyze: vergleichen (Platon vs. Aristoteles, Hume vs. Kant), unterscheiden (deontologische vs. konsequentialistische Ethik), aus der Quelle argumentieren.
Verben Bloom-Evaluate: eine These kritisieren, die interne Kohärenz eines Systems bewerten, eine Gegenargumentation aufbauen.
Beispiele: Trolley-Dilemma, Lügner-Paradoxon, Leib-Seele-Problem.''',
    Discipline.history: '''DISZIPLIN: Geschichte.
Verben Bloom-Apply: ein Ereignis korrekt zuordnen, eine periodisierende Kategorie auf ein Ereignis anwenden, unmittelbare vs. ferne Ursache lokalisieren.
Verben Bloom-Analyze: wirtschaftliche/politische/soziale Ursachen unterscheiden, Französische vs. Amerikanische Revolution vergleichen, eine Primärquelle interpretieren, Bias erkennen.
Verben Bloom-Evaluate: die Auswirkung eines Ereignisses bewerten, eine historiographische These kritisieren, mit dokumentarischen Belegen argumentieren.
Vermeide bloße Jahreszahlen: frage nach WARUM + WIE, nicht nur WANN.''',
    Discipline.generic: '''DISZIPLIN: generisch.
Verben Bloom-Apply: anwenden, berechnen, vorhersagen, klassifizieren.
Verben Bloom-Analyze: unterscheiden, vergleichen, interpretieren, ableiten.
Verben Bloom-Evaluate: bewerten, kritisieren, argumentieren, begründen.
Ohne spezifisches Fachgebiet, bevorzuge Fragen, die mehrstufiges Denken erfordern und die anhand der Notizen des Clusters lösbar sind.
Vermeide generische Fragen wie "Was ist X?" (Nur Erinnern).''',
  },
  'ja': {
    Discipline.physics: '''分野: 物理学。
動詞 Bloom-Apply: 計算する (合力、モーメント、エネルギー)、予測する (軌道、時刻t+Δtにおける位置)、適用する (ニュートンの第二法則、保存則)。
動詞 Bloom-Analyze: 導出する (運動方程式)、区別する (弾性/非弾性)、比較する (慣性系と非慣性系)。
動詞 Bloom-Evaluate: 系の安定性を評価する、モデル仮説を批判的に検討する。
好ましいシナリオ: 摩擦のある斜面、1次元/2次元衝突、調和振動子、RLC回路、カルノーサイクルの熱力学。''',
    Discipline.math: '''分野: 数学。
Bloom-Apply 動詞: 解く (方程式, 連立方程式), 計算する (極限, 導関数, 部分積分/置換積分), 適用する (ロピタルの定理, ラグランジュの定理)。
Bloom-Analyze 動詞: 証明する (数学的帰納法で, 背理法で, 対偶で), 反例を見つける, 同値性を示す, 不連続点を分類する。
Bloom-Evaluate 動詞: 証明を批判する, 定理の一般性を評価する。
「計算する」だけを唯一の動詞としない — 試験の数学は証明である。''',
    Discipline.chemistry: '''分野: 化学.
動詞 Bloom-Apply: 平衡させる (酸化還元反応, 中和反応), 計算する (モル濃度, pH, 濃度), 予測する (反応生成物).
動詞 Bloom-Analyze: 区別する (強酸/弱酸, SN1/SN2), 分子メカニズムを説明する, 官能基によって化合物を分類する.
動詞 Bloom-Evaluate: 熱力学的自発性 (ΔG) を評価する, 合成経路を批判的に検討する.
常に分子の因果関係と表現レベル (分子レベル/巨視的レベル/記号レベル) に着目せよ.''',
    Discipline.biology: '''分野: 生物学。
動詞 Bloom-Apply: 適用する (ハーディ・ワインバーグの法則、メンデルの法則)、予測する (F2世代の表現型、突然変異の結果)、計算する (対立遺伝子頻度)。
動詞 Bloom-Analyze: 区別する (有糸分裂と減数分裂、原核生物と真核生物)、機能を説明する (細胞小器官、システム)、比較する (自然選択と遺伝的浮動)。
動詞 Bloom-Evaluate: 進化仮説の証拠を評価する、実験モデルを批判的に検討する。
例: ATP合成酵素、遺伝子発現制御、恒常性、生態系。''',
    Discipline.medicine: '''分野: 医学。
動詞 Bloom-Apply: 診断する (症状・兆候に基づいて)、提案する (第一選択治療)、適用する (DSM基準、ESCガイドライン)。
動詞 Bloom-Analyze: 鑑別する (鑑別診断)、解釈する (臨床検査、画像診断)、根本的な病態生理を評価する。
動詞 Bloom-Evaluate: 治療法を批判的に評価する、予後を評価する、根拠に基づいて考察する (RCT vs 症例報告)。
具体的な臨床シナリオ (病歴 + 検査 + 予測される予後を含む)。''',
    Discipline.law: '''分野: 法律。
動詞 Bloom-Apply: (法規を具体的な事例に) 適用する、(法的構成要件を) 認定する、(責任を) 特定する。
動詞 Bloom-Analyze: (故意と過失、契約と単独行為を) 区別する、(判例を) 比較する、法意から論じる。
動詞 Bloom-Evaluate: 行為の適法性を評価する、判例解釈を批判する。
好ましいシナリオ: 明確な構成要件要素を持つ具体的な事例と、適用可能な法規（民法、刑法、憲法）。''',
    Discipline.economics: '''分野: 経済学。
行動動詞 Bloom-Apply: 計算する（弾力性、GDP、余剰）、適用する（完全競争モデル、IS-LMモデル）、予測する（金融政策/財政政策の効果）。
行動動詞 Bloom-Analyze: 区別する（代替効果 vs 所得効果）、比較する（市場体制）、解釈する（マクロ経済データ）。
行動動詞 Bloom-Evaluate: 評価する（経済政策）、批判的に検討する（モデルの仮定：完全な移動性、合理性）。
例：需要と供給のグラフ + 現実的な数値データ。''',
    Discipline.philosophy: '''分野: 哲学。
動詞 Bloom-Apply: 適用する（カント的範疇を事例に、功利主義の原則）、分類する（哲学者を学派別に、テキストを流派別に）。
動詞 Bloom-Analyze: 比較する（プラトンとアリストテレス、ヒュームとカント）、区別する（義務論的倫理と帰結主義的倫理）、資料に基づいて論じる。
動詞 Bloom-Evaluate: テーゼを批判する、システムの内的整合性を評価する、反論を構築する。
例: トロッコ問題、嘘つきのパラドックス、心身問題。''',
    Discipline.history: '''分野: 歴史.
Bloom-Apply 動詞: 出来事の年代を正しく特定する, （事実に時代区分を）適用する, （近因と遠因を）特定する.
Bloom-Analyze 動詞: （経済的・政治的・社会的要因を）区別する, （フランス革命とアメリカ独立革命を）比較する, 一次資料を解釈する, 偏見を特定する.
Bloom-Evaluate 動詞: 出来事の影響を評価する, 歴史学の学説を批判的に検討する, 文献的証拠に基づいて論じる.
単なる日付の羅列を避ける: 「いつ」だけでなく、「なぜ」と「どのように」を問う。''',
    Discipline.generic: '''分野: 汎用。
Bloom-Apply 動詞: 適用する, 計算する, 予測する, 分類する。
Bloom-Analyze 動詞: 区別する, 比較する, 解釈する, 導き出す。
Bloom-Evaluate 動詞: 評価する, 批判する, 論じる, 正当化する。
特定の専門分野に限定せず、多段階の思考を要し、クラスターのノートで解決可能な問題を優先する。
「Xとは何か？」のような一般的な質問（記憶のみ）は避ける。''',
  },
  'ko': {
    Discipline.physics: '''과목: 물리학.
동사 Bloom-Apply: 계산하다 (알짜힘, 운동량, 에너지), 예측하다 (경로, t+Δt 시점의 위치), 적용하다 (뉴턴 제2법칙, 보존 법칙).
동사 Bloom-Analyze: 유도하다 (운동 방정식), 구분하다 (탄성/비탄성), 비교하다 (관성계 vs 비관성계).
동사 Bloom-Evaluate: 시스템의 안정성을 평가하다, 모델 가설을 비판하다.
선호하는 시나리오: 마찰이 있는 경사면, 1차원/2차원 충돌, 조화 진동자, RLC 회로, 카르노 순환 열역학.''',
    Discipline.math: '''분야: 수학.
동사 Bloom-Apply: 풀다 (방정식, 연립방정식), 계산하다 (극한,
미분, 부분적분/치환적분), 적용하다 (로피탈의 정리, 라그랑주의 정리).
동사 Bloom-Analyze: 증명하다 (귀납법으로, 귀류법으로, 대우법으로),
반례를 찾다, 동치임을 보이다, 불연속점을 분류하다.
동사 Bloom-Evaluate: 증명을 비판하다, 정리의 일반성을 평가하다.
"계산하다"만을 유일한 동사로 사용해서는 안 됩니다 — 시험 수학은 증명입니다.''',
    Discipline.chemistry: '''분야: 화학.
동사 Bloom-Apply: 균형을 맞추다 (산화-환원 반응, 중화 반응), 계산하다 (몰 농도, pH, 농도), 예측하다 (반응 생성물).
동사 Bloom-Analyze: 구별하다 (강산/약산, SN1/SN2), 분자 메커니즘을 설명하다, 작용기에 따라 화합물을 분류하다.
동사 Bloom-Evaluate: 열역학적 자발성 (ΔG)을 평가하다, 합성 경로를 비판적으로 검토하다.
항상 분자적 인과 관계와 표현 수준(분자적/거시적/상징적)을 찾아라.''',
    Discipline.biology: '''분야: 생물학.
동사 Bloom-Apply: 적용하다 (하디-바인베르크, 멘델의 법칙), 예측하다 (F2 표현형, 돌연변이 결과), 계산하다 (대립유전자 빈도).
동사 Bloom-Analyze: 구별하다 (유사분열/감수분열, 원핵생물/진핵생물), 기능을 설명하다 (세포소기관, 시스템), 비교하다 (자연 선택 대 유전적 부동).
동사 Bloom-Evaluate: 진화 가설의 증거를 평가하다, 실험 모델을 비판하다.
예시: ATP 합성효소, 유전자 조절, 항상성, 생태계.''',
    Discipline.medicine: '''분야: 의학.
동사 Bloom-Apply: 진단하다 (증상/징후를 기반으로), 제안하다 (일차 치료법), 적용하다 (DSM 기준, ESC 가이드라인).
동사 Bloom-Analyze: 구분하다 (감별 진단), 해석하다 (실험실 검사, 영상), 평가하다 (기저 병태생리).
동사 Bloom-Evaluate: 비판하다 (치료법), 평가하다 (예후), 논하다 (증거 기반: RCT vs 증례 보고).
구체적인 임상 시나리오 (병력 + 검사 + 예상 예후 포함).''',
    Discipline.law: '''분야: 법.
동사 Bloom-Apply: 적용하다 (규범을 구체적 사례에), 규정하다 (법적 구성요건을), 확인하다 (책임을).
동사 Bloom-Analyze: 구별하다 (고의/과실, 계약/단독행위), 비교하다 (판례를), 논증하다 (입법 취지에 근거하여).
동사 Bloom-Evaluate: 평가하다 (행위의 적법성을), 비판하다 (판례 해석을).
선호하는 시나리오: 명확한 법적 구성요건을 갖춘 구체적 사례 + 적용 가능한 규범 (민법, 형법, 헌법).''',
    Discipline.economics: '''분야: 경제학.
동사 Bloom-Apply: 탄력성, GDP, 잉여 계산, 완전 경쟁 모델, IS-LM 적용, 통화/재정 정책 효과 예측.
동사 Bloom-Analyze: 대체 효과와 소득 효과 구분, 시장 구조 비교, 거시 경제 데이터 해석.
동사 Bloom-Evaluate: 경제 정책 평가, 모델 가정(완전 이동성, 합리성) 비판.
수요-공급 곡선 그래프 및 현실적인 수치 데이터 예시.''',
    Discipline.philosophy: '''분야: 철학.
동사 Bloom-Apply: 적용하다 (칸트 범주를 특정 사례에, 공리주의 원칙을), 분류하다 (철학자를 사조별로, 텍스트를 학파별로).
동사 Bloom-Analyze: 비교하다 (플라톤과 아리스토텔레스, 흄과 칸트), 구분하다 (의무론적 윤리와 결과론적 윤리), 자료를 바탕으로 논증하다.
동사 Bloom-Evaluate: 주장을 비판하다, 체계의 내적 일관성을 평가하다, 반론을 구성하다.
예시: 트롤리 딜레마, 거짓말쟁이 역설, 심신 문제.''',
    Discipline.history: '''분야: 역사.
블룸 동사 - 적용: 주어진 사건의 정확한 연대를 파악하다, 사실에 시대 구분 범주를 적용하다, 근접 원인과 원격 원인을 구분하다.
블룸 동사 - 분석: 경제적/정치적/사회적 원인을 구별하다, 프랑스 혁명과 미국 혁명을 비교하다, 1차 사료를 해석하다, 편향을 식별하다.
블룸 동사 - 평가: 사건의 영향을 평가하다, 역사학적 주장을 비판하다, 문서 증거를 바탕으로 논증하다.
단순한 연대 암기를 피하고: '언제'뿐만 아니라 '왜'와 '어떻게'를 질문하라.''',
    Discipline.generic: '''분야: 일반.
Bloom-Apply 동사: 적용하다, 계산하다, 예측하다, 분류하다.
Bloom-Analyze 동사: 구별하다, 비교하다, 해석하다, 도출하다.
Bloom-Evaluate 동사: 평가하다, 비판하다, 논증하다, 정당화하다.
특정 분야가 없는 경우, 다단계 추론을 요구하고 클러스터 노트로 해결 가능한 질문을 우선시한다.
"X는 무엇인가?"와 같은 일반적인 질문은 피한다 (Remember-only).''',
  },
  'zh': {
    Discipline.physics: '''学科：物理。
动词 Bloom-Apply: 计算 (净力, 力矩, 能量), 预测 (轨迹, t+Δt时的位置), 应用 (牛顿第二定律, 守恒定律)。
动词 Bloom-Analyze: 推导 (运动方程), 区分 (弹性/非弹性), 比较 (惯性系与非惯性系)。
动词 Bloom-Evaluate: 评估系统稳定性, 批判模型假设。
偏好场景: 带摩擦力的斜面, 一维/二维碰撞, 简谐振子, RLC电路, 卡诺循环热力学。''',
    Discipline.math: '''学科：数学。
动词 Bloom-Apply: 求解 (方程, 方程组), 计算 (极限, 导数, 分部积分/换元积分), 应用 (洛必达法则, 拉格朗日定理)。
动词 Bloom-Analyze: 证明 (归纳法, 反证法, 逆否证法), 寻找反例, 证明等价性, 分类不连续点。
动词 Bloom-Evaluate: 批判一个证明, 评估一个定理的普适性。
切勿仅以“计算”作为唯一动词——考试数学是论证。''',
    Discipline.chemistry: '''学科：化学。
动词 Bloom-Apply: 平衡 (氧化还原反应, 中和反应), 计算 (摩尔浓度, pH值, 浓度), 预测 (反应产物)。
动词 Bloom-Analyze: 区分 (强酸/弱酸, SN1/SN2反应), 解释分子机制, 按官能团对化合物进行分类。
动词 Bloom-Evaluate: 评估热力学自发性 (ΔG), 评价合成路线。
务必探究分子因果关系以及表征层面 (分子/宏观/符号)。''',
    Discipline.biology: '''学科: 生物学。
布鲁姆应用动词: 应用 (哈迪-温伯格定律, 孟德尔遗传定律), 预测 (F2表型, 突变结果), 计算 (等位基因频率)。
布鲁姆分析动词: 区分 (有丝分裂/减数分裂, 原核生物/真核生物), 解释功能 (细胞器, 系统), 比较 (自然选择 与 遗传漂变)。
布鲁姆评估动词: 评估进化假说的证据, 批判性评价实验模型。
例子: ATP合酶, 基因调控, 内稳态, 生态系统。''',
    Discipline.medicine: '''学科：医学。
动词 Bloom-Apply: 诊断 (基于症状/体征), 提出 (一线治疗方案), 应用 (DSM标准, ESC指南)。
动词 Bloom-Analyze: 鉴别 (鉴别诊断), 解读 (实验室检查, 影像学), 评估潜在的病理生理学。
动词 Bloom-Evaluate: 批判性评估治疗方案, 评估预后, 基于证据推理 (随机对照试验 vs 病例报告)。
具体的临床场景，包含病史 + 检查 + 预期预后。''',
    Discipline.law: '''学科：法律。
动词 Bloom-Apply: 适用 (规范于具体案例), 定性 (法律事实), 认定 (责任)。
动词 Bloom-Analyze: 区分 (故意/过失, 合同/单方行为), 比较 (司法判例), 从立法本意论证。
动词 Bloom-Evaluate: 评估 (某项行为的合法性), 评析 (司法解释)。
偏好场景: 事实要素明确的具体案例 + 适用法律规范 (民法典, 刑法, 宪法)。''',
    Discipline.economics: '''学科: 经济学。
Bloom-Apply 动词: 计算 (弹性、GDP、剩余), 应用 (完全竞争模型、IS-LM模型), 预测货币/财政政策的影响。
Bloom-Analyze 动词: 区分 (替代效应与收入效应), 比较 (市场结构), 解读宏观经济数据。
Bloom-Evaluate 动词: 评估经济政策, 批判模型假设 (完全流动性、理性)。
示例包含供求图 + 实际数值数据。''',
    Discipline.philosophy: '''学科：哲学。
动词 Bloom-Apply: 应用 (将康德范畴应用于具体案例，运用功利主义原则)，分类 (按流派划分哲学家，按学派归类文本)。
动词 Bloom-Analyze: 比较 (柏拉图与亚里士多德，休谟与康德)，区分 (义务论伦理学与结果论伦理学)，援引文献进行论证。
动词 Bloom-Evaluate: 批判一个论点，评估一个系统的内部一致性，构建一个反驳论证。
示例：电车难题，说谎者悖论，心身问题。''',
    Discipline.history: '''学科：历史。
布鲁姆应用动词：正确给定一个事件，应用（历史分期类别于某一史实），定位（近因与远因）。
布鲁姆分析动词：区分（经济/政治/社会原因），比较（法国大革命与美国独立战争），解读一手史料，识别偏见。
布鲁姆评估动词：评估某一事件的影响，批判史学论点，根据文献证据进行论证。
避免死记硬背日期：提问为什么 + 如何，而不仅仅是何时。''',
    Discipline.generic: '''学科: 通用。
动词 Bloom-Apply: 应用, 计算, 预测, 分类。
动词 Bloom-Analyze: 区分, 比较, 解释, 推导。
动词 Bloom-Evaluate: 评估, 批判, 论证, 证明。
不限于特定领域，优先选择需要多步骤推理且可从集群笔记中解决的问题。
避免诸如“什么是X？”之类的通用问题 (仅记忆层面)。''',
  },
  'ar': {
    Discipline.physics: '''التخصص: الفيزياء.
أفعال Bloom-Apply: احسب (القوة المحصلة، العزم، الطاقة)، توقع (المسار، الموضع عند t+Δt)، طبّق (قانون نيوتن الثاني، قوانين الحفظ).
أفعال Bloom-Analyze: اشتق (معادلة الحركة)، ميّز (مرن/غير مرن)، قارن (الأنظمة القصورية مقابل غير القصورية).
أفعال Bloom-Evaluate: قيّم استقرار نظام، انقد فرضية نموذج.
السيناريوهات المفضلة: مستوى مائل مع احتكاك، تصادمات أحادية/ثنائية الأبعاد، المذبذب التوافقي، دوائر RLC، الديناميكا الحرارية لدورة كارنو.''',
    Discipline.math: '''التخصص: الرياضيات.
أفعال Bloom-Apply: حل (معادلة، نظام)، احسب (نهاية، مشتقة، تكامل بالتجزئة/بالتعويض)، طبق (قاعدة لوبيتال، مبرهنة لاغرانج).
أفعال Bloom-Analyze: أثبت (بالاستقراء، بالخلف، بالنقيض)، أوجد مثالاً مضاداً، بين التكافؤ، صنف نقاط الانقطاع.
أفعال Bloom-Evaluate: انقد برهاناً، قيم عمومية مبرهنة.
لا تكتفِ بـ "احسب" كفعل وحيد أبداً — رياضيات الامتحان هي اختبار.''',
    Discipline.chemistry: '''التخصص: الكيمياء.
أفعال Bloom-Apply: وازن (تفاعل الأكسدة والاختزال، التحييد)، احسب (المولارية، الرقم الهيدروجيني (pH)، التركيز)، تنبأ (بناتج التفاعل).
أفعال Bloom-Analyze: ميّز (حمض قوي/ضعيف، SN1/SN2)، اشرح الآلية الجزيئية، صنّف المركبات حسب المجموعة الوظيفية.
أفعال Bloom-Evaluate: قيّم التلقائية الديناميكية الحرارية (ΔG)، انقد مسار تخليق.
ابحث دائمًا عن السببية الجزيئية ومستوى التمثيل (جزيئي/عياني/رمزي).''',
    Discipline.biology: '''التخصص: علم الأحياء.
أفعال بلوم-تطبيق: طبق (هاردي-فاينبرغ، قوانين مندل)، توقع (الأنماط الظاهرية للجيل F2، نتيجة الطفرة)، احسب (ترددات الأليلات).
أفعال بلوم-تحليل: ميز (الانقسام المتساوي/المنصف، بدائيات النوى/حقيقيات النوى)، اشرح وظيفة (عضية، نظام)، قارن (الانتخاب الطبيعي مقابل الانجراف الوراثي).
أفعال بلوم-تقييم: قيم الأدلة على فرضية تطورية، انقد نموذجًا تجريبيًا.
أمثلة: سينثاز ATP، تنظيم جيني، استتباب، أنظمة بيئية.''',
    Discipline.medicine: '''التخصص: الطب.
أفعال Bloom-Apply: شخّص (بناءً على الأعراض/العلامات)، اقترح (علاج الخط الأول)، طبّق (معايير DSM، إرشادات ESC).
أفعال Bloom-Analyze: ميّز (التشخيص التفريقي)، فسّر (الفحوصات المخبرية، التصوير الطبي)، قيّم الفيزيولوجيا المرضية الكامنة.
أفعال Bloom-Evaluate: انتقد علاجًا، قيّم المآل، ناقش الأدلة (RCT مقابل تقارير الحالات).
سيناريوهات سريرية ملموسة تتضمن السيرة المرضية + الفحوصات + المآل المتوقع.''',
    Discipline.law: '''التخصص: القانون.
أفعال Bloom-Apply: يطبق (القاعدة القانونية على الحالة الواقعية)، يُكيّف (الواقعة القانونية)، يحدد (المسؤولية).
أفعال Bloom-Analyze: يميز (بين القصد/الخطأ، العقد/التصرف الانفرادي)، يقارن (السوابق القضائية)، يستدل من (العلة التشريعية).
أفعال Bloom-Evaluate: يُقيّم (مشروعية فعل)، ينقد (تفسيراً قضائياً).
سيناريوهات مفضلة: حالات واقعية ذات عناصر واضحة للواقعة القانونية + نصوص قانونية قابلة للتطبيق (القانون المدني، الجنائي، الدستور).''',
    Discipline.economics: '''التخصص: الاقتصاد.
أفعال Bloom-Apply: احسب (المرونة، الناتج المحلي الإجمالي، الفائض)، طبق (نموذج المنافسة الكاملة، IS-LM)، توقع تأثير سياسة نقدية/مالية.
أفعال Bloom-Analyze: ميز (تأثير الإحلال مقابل الدخل)، قارن (أنظمة السوق)، فسر البيانات الاقتصادية الكلية.
أفعال Bloom-Evaluate: قيم سياسة اقتصادية، انقد افتراضًا لنموذج (التنقل التام، العقلانية).
أمثلة تتضمن رسوم بيانية للعرض والطلب + بيانات رقمية واقعية.''',
    Discipline.philosophy: '''التخصص: الفلسفة.
أفعال Bloom-Apply: طبق (فئة كانطية على حالة، مبدأ نفعي)، صنف (فيلسوفًا حسب التيار، نصًا حسب المدرسة).
أفعال Bloom-Analyze: قارن (أفلاطون مقابل أرسطو، هيوم مقابل كانط)، ميز (بين الأخلاق الواجبية والأخلاق العواقبية)، استدل من المصدر.
أفعال Bloom-Evaluate: انقد أطروحة، قيم الاتساق الداخلي لنظام، ابنِ حجة مضادة.
أمثلة: معضلة العربة، مفارقة الكاذب، مشكلة العقل والجسد.''',
    Discipline.history: '''التخصص: التاريخ.
أفعال Bloom-Apply: عند إعطاء حدث بشكل صحيح، طبق (فئة تصنيف زمني على حقيقة)، حدد (السبب المباشر مقابل السبب البعيد).
أفعال Bloom-Analyze: ميز (الأسباب الاقتصادية/السياسية/الاجتماعية)، قارن (الثورة الفرنسية مقابل الأمريكية)، فسّر مصدرًا أساسيًا، حدد التحيز.
أفعال Bloom-Evaluate: قيّم تأثير حدث ما، انقد أطروحة تاريخية، برهن بالاستناد إلى الأدلة الوثائقية.
تجنب التواريخ العقيمة: اسأل لماذا + كيف، وليس فقط متى.''',
    Discipline.generic: '''التخصص: عامة.
أفعال Bloom-Apply: طبق، احسب، تنبأ، صنف.
أفعال Bloom-Analyze: ميز، قارن، فسر، استنتج.
أفعال Bloom-Evaluate: قيم، انقد، ناقش، برر.
في غياب مجال محدد، فضل الأسئلة التي تتطلب تفكيراً متعدد الخطوات وتكون قابلة للحل من ملاحظات المجموعة.
تجنب الأسئلة العامة مثل "ما هو X؟" (Remember-only).''',
  },
  'hi': {
    Discipline.physics: '''विषय: भौतिकी।
क्रियाएँ Bloom-Apply: गणना करें (शुद्ध बल, संवेग, ऊर्जा), पूर्वानुमान लगाएं (प्रक्षेपवक्र, t+Δt पर स्थिति), लागू करें (न्यूटन का दूसरा नियम, संरक्षण)।
क्रियाएँ Bloom-Analyze: व्युत्पन्न करें (गति का समीकरण), अंतर करें (प्रत्यास्थ/अप्रत्यास्थ), तुलना करें (जड़त्वीय बनाम अजड़त्वीय निकाय)।
क्रियाएँ Bloom-Evaluate: किसी निकाय की स्थिरता का मूल्यांकन करें, एक मॉडल परिकल्पना की आलोचना करें।
पसंदीदा परिदृश्य: घर्षण सहित आनत तल, 1D/2D टक्करें, सरल आवर्ती दोलक, RLC परिपथ, कार्नो चक्र की ऊष्मागतिकी।''',
    Discipline.math: '''विषय: गणित।
क्रियाएँ Bloom-Apply: हल करें (समीकरण, निकाय), गणना करें (सीमा, अवकलज, खंडशः/प्रतिस्थापन द्वारा समाकलन), लागू करें (डी ला'हॉपिटल का नियम, लाग्रेंज का प्रमेय)।
क्रियाएँ Bloom-Analyze: सिद्ध करें (प्रेरण द्वारा, विरोधाभास द्वारा, प्रतिधनात्मक द्वारा), एक प्रतिउदाहरण खोजें, तुल्यता दर्शाएँ, असंततताओं का वर्गीकरण करें।
क्रियाएँ Bloom-Evaluate: एक प्रमाण की आलोचना करें, एक प्रमेय की व्यापकता का मूल्यांकन करें।
केवल 'गणना करें' को एकमात्र क्रिया के रूप में कभी न रखें — परीक्षा का गणित एक प्रमाण है।''',
    Discipline.chemistry: '''विषय: रसायन विज्ञान।
क्रियाएँ Bloom-Apply: संतुलित करें (रेडॉक्स अभिक्रिया, उदासीनीकरण), गणना करें (मोलरता, पीएच, सांद्रता), भविष्यवाणी करें (अभिक्रिया उत्पाद)।
क्रियाएँ Bloom-Analyze: अंतर करें (प्रबल/दुर्बल अम्ल, SN1/SN2), आणविक क्रियाविधि समझाएँ, यौगिकों को क्रियात्मक समूह के आधार पर वर्गीकृत करें।
क्रियाएँ Bloom-Evaluate: ऊष्मागतिक स्वतःप्रवर्तन का मूल्यांकन करें (ΔG), एक संश्लेषण मार्ग की आलोचना करें।
हमेशा आणविक कारणता और निरूपण के स्तर (आणविक/स्थूल/प्रतीकात्मक) पर ध्यान दें।''',
    Discipline.biology: '''विषय: जीव विज्ञान।
क्रियाएँ Bloom-Apply: लागू करें (हार्डी-वेनबर्ग, मेंडल के नियम), भविष्यवाणी करें (F2 फेनोटाइप, उत्परिवर्तन का परिणाम), गणना करें (एलीलिक आवृत्तियाँ)।
क्रियाएँ Bloom-Analyze: अंतर करें (माइटोसिस/अर्धसूत्रीविभाजन, प्रोकैरियोट्स/यूकैरियोट्स), कार्य समझाएँ (कोशिकांग, तंत्र), तुलना करें (प्राकृतिक चयन बनाम आनुवंशिक बहाव)।
क्रियाएँ Bloom-Evaluate: एक विकासात्मक परिकल्पना के साक्ष्य का मूल्यांकन करें, एक प्रायोगिक मॉडल की आलोचना करें।
उदाहरण: एटीपी-सिंथेज़, जीन विनियमन, समस्थापन, पारिस्थितिकी तंत्र।''',
    Discipline.medicine: '''विषय: चिकित्सा।
क्रियाएँ Bloom-Apply: निदान करें (लक्षणों/संकेतों के आधार पर), सुझाएँ (प्रथम-पंक्ति चिकित्सा), लागू करें (DSM मानदंड, ESC दिशानिर्देश)।
क्रियाएँ Bloom-Analyze: अंतर करें (विभेदक निदान), व्याख्या करें (प्रयोगशाला परीक्षण, इमेजिंग), अंतर्निहित विकृति-विज्ञान का आकलन करें।
क्रियाएँ Bloom-Evaluate: किसी उपचार की आलोचना करें, पूर्वानुमान (प्रोग्नोसिस) का मूल्यांकन करें, साक्ष्य पर तर्क करें (RCT बनाम केस रिपोर्ट)।
ठोस नैदानिक ​​परिदृश्य जिसमें रोगी का इतिहास + परीक्षण + अपेक्षित पूर्वानुमान शामिल हों।''',
    Discipline.law: '''विषय: विधि।
क्रियाएँ Bloom-Apply: लागू करें (नियम को विशिष्ट मामले पर), वर्गीकृत करें (कानूनी तथ्य-स्थिति), निर्धारित करें (उत्तरदायित्व)।
क्रियाएँ Bloom-Analyze: अंतर करें (इरादा/लापरवाही, अनुबंध/एकतरफा कार्य), तुलना करें (न्यायिक पूर्व-निर्णयों की), विधि के मूल सिद्धांत से तर्क दें।
क्रियाएँ Bloom-Evaluate: किसी कार्य की वैधता का मूल्यांकन करें, किसी न्यायिक व्याख्या की आलोचना करें।
पसंदीदा परिदृश्य: स्पष्ट तथ्य-स्थितियों वाले वास्तविक मामले + लागू होने वाले नियम (दीवानी संहिता, दंड संहिता, संविधान)।''',
    Discipline.economics: '''विषय: अर्थशास्त्र।
क्रियाएँ Bloom-Apply: गणना करें (लोच, सकल घरेलू उत्पाद, अधिशेष), लागू करें (पूर्ण प्रतिस्पर्धा मॉडल, IS-LM), मौद्रिक/राजकोषीय नीति के प्रभाव की भविष्यवाणी करें।
क्रियाएँ Bloom-Analyze: अंतर करें (प्रतिस्थापन प्रभाव बनाम आय प्रभाव), तुलना करें (बाजार व्यवस्थाओं), समष्टि-आर्थिक डेटा की व्याख्या करें।
क्रियाएँ Bloom-Evaluate: एक आर्थिक नीति का मूल्यांकन करें, एक मॉडल की धारणा की आलोचना करें (पूर्ण गतिशीलता, तार्किकता)।
मांग-आपूर्ति ग्राफ + वास्तविक संख्यात्मक डेटा के साथ उदाहरण।''',
    Discipline.philosophy: '''विषय: दर्शनशास्त्र।
ब्लूम-अप्लाई क्रियाएँ: लागू करें (किसी मामले पर कांटियन श्रेणी, उपयोगितावादी सिद्धांत), वर्गीकृत करें (दार्शनिक को विचारधारा के अनुसार, पाठ को संप्रदाय के अनुसार)।
ब्लूम-एनालाइज क्रियाएँ: तुलना करें (प्लेटो बनाम अरस्तू, ह्यूम बनाम कांट), अंतर करें (कर्तव्यमूलक नैतिकता बनाम परिणामवादी नैतिकता), स्रोत से तर्क दें।
ब्लूम-इवैल्यूएट क्रियाएँ: किसी थीसिस की आलोचना करें, किसी प्रणाली की आंतरिक संगति का मूल्यांकन करें, एक प्रति-तर्क निर्मित करें।
उदाहरण: ट्रॉली दुविधा, मिथ्यावादी विरोधाभास, मन-शरीर समस्या।''',
    Discipline.history: '''विषय: इतिहास।
क्रियाएँ Bloom-Apply: सही ढंग से किसी घटना का विवरण दें, लागू करें (किसी तथ्य पर काल-निर्धारण श्रेणी), पहचानें (निकटवर्ती कारण बनाम दूरस्थ कारण)।
क्रियाएँ Bloom-Analyze: अंतर करें (आर्थिक/राजनीतिक/सामाजिक कारण), तुलना करें (फ्रांसीसी क्रांति बनाम अमेरिकी क्रांति), एक प्राथमिक स्रोत की व्याख्या करें, पूर्वाग्रह की पहचान करें।
क्रियाएँ Bloom-Evaluate: किसी घटना के प्रभाव का मूल्यांकन करें, एक इतिहासलेखीय शोध-प्रबंध की आलोचना करें, दस्तावेजी साक्ष्य से तर्क दें।
निष्फल तिथियों से बचें: पूछें क्यों + कैसे, न कि केवल कब।''',
    Discipline.generic: '''विषय: सामान्य।
क्रियाएँ Bloom-Apply: लागू करें, गणना करें, भविष्यवाणी करें, वर्गीकृत करें।
क्रियाएँ Bloom-Analyze: अंतर करें, तुलना करें, व्याख्या करें, व्युत्पन्न करें।
क्रियाएँ Bloom-Evaluate: मूल्यांकन करें, आलोचना करें, तर्क दें, औचित्य सिद्ध करें।
बिना किसी विशिष्ट क्षेत्र के, ऐसे प्रश्नों को प्राथमिकता दें जिनमें बहु-चरणीय तर्क की आवश्यकता हो और जो क्लस्टर के नोट्स से हल किए जा सकें।
'X क्या है?' जैसे सामान्य प्रश्नों से बचें (Remember-only)।''',
  },
  'ru': {
    Discipline.physics: '''ДИСЦИПЛИНА: физика.
Глаголы Bloom-Apply: вычисли (равнодействующую силу, момент, энергию), предскажи (траекторию, положение в момент времени t+Δt), примени (второй закон Ньютона, законы сохранения).
Глаголы Bloom-Analyze: выведи (уравнение движения), различи (упругое/неупругое), сравни (инерциальные и неинерциальные системы отсчета).
Глаголы Bloom-Evaluate: оцени устойчивость системы, критикуй модельную гипотезу.
Предпочтительные сценарии: наклонная плоскость с трением, столкновения 1D/2D, гармонический осциллятор, RLC-цепи, термодинамика цикла Карно.''',
    Discipline.math: '''ДИСЦИПЛИНА: математика.
Глаголы Bloom-Apply: реши (уравнение, систему), вычисли (предел, производную, интеграл по частям/заменой), примени (правило Лопиталя, теорему Лагранжа).
Глаголы Bloom-Analyze: докажи (индукцией, от противного, методом контрапозиции), найди контрпример, покажи эквивалентность, классифицируй разрывы.
Глаголы Bloom-Evaluate: критикуй доказательство, оцени общность теоремы.
Никогда не используй только "вычисли" как единственный глагол — экзаменационная математика — это проверка.''',
    Discipline.chemistry: '''ДИСЦИПЛИНА: химия.
Глаголы Bloom-Apply: уравняй (окислительно-восстановительная реакция, нейтрализация), вычисли (молярность, pH, концентрация), предскажи (продукт реакции).
Глаголы Bloom-Analyze: различи (сильная/слабая кислота, SN1/SN2), объясни молекулярный механизм, классифицируй соединения по функциональной группе.
Глаголы Bloom-Evaluate: оцени термодинамическую спонтанность (ΔG), критикуй путь синтеза.
ВСЕГДА ищи молекулярную причинность и уровень представления (молекулярный/макроскопический/символический).''',
    Discipline.biology: '''ДИСЦИПЛИНА: биология.
Глаголы Bloom-Apply: применяй (закон Харди-Вайнберга, законы Менделя), предскажи (фенотипы F2, исход мутации), вычисли (частоты аллелей).
Глаголы Bloom-Analyze: различай (митоз/мейоз, прокариоты/эукариоты), объясни функцию (органеллы, системы), сравни (естественный отбор и генетический дрейф).
Глаголы Bloom-Evaluate: оцени доказательства эволюционной гипотезы, критикуй экспериментальную модель.
Примеры: АТФ-синтаза, генная регуляция, гомеостаз, экосистемы.''',
    Discipline.medicine: '''ДИСЦИПЛИНА: медицина.
Глаголы Bloom-Apply: диагностируй (на основе симптомов/признаков), предложи (терапию первой линии), примени (критерии DSM, рекомендации ESC).
Глаголы Bloom-Analyze: дифференцируй (дифференциальный диагноз), интерпретируй (лабораторные анализы, визуализацию), оцени лежащую в основе патофизиологию.
Глаголы Bloom-Evaluate: критикуй лечение, оцени прогноз, рассуждай на основе доказательств (РКИ против описания случая).
Конкретные клинические сценарии с анамнезом + результатами обследований + ожидаемым прогнозом.''',
    Discipline.law: '''ДИСЦИПЛИНА: право.
Глаголы Bloom-Apply: применить (норму к конкретному случаю), квалифицировать (юридический состав), установить (ответственность).
Глаголы Bloom-Analyze: различать (умысел/неосторожность, договор/одностороннюю сделку), сравнивать (судебные прецеденты), обосновывать (смысл закона).
Глаголы Bloom-Evaluate: оценивать (законность акта), критиковать (судебное толкование).
Предпочтительные сценарии: конкретные случаи с четкими элементами юридического состава и применимые нормы (гражданский, уголовный кодексы, конституция).''',
    Discipline.economics: '''ДИСЦИПЛИНА: экономика.
Глаголы Bloom-Apply: рассчитай (эластичность, ВВП, излишек), примени (модель совершенной конкуренции, IS-LM), предскажи эффект денежно-кредитной/фискальной политики.
Глаголы Bloom-Analyze: различи (эффект замещения vs дохода), сравни (рыночные режимы), интерпретируй макроэкономические данные.
Глаголы Bloom-Evaluate: оцени экономическую политику, критикуй допущение модели (идеальная мобильность, рациональность).
Примеры с графиками спроса и предложения + реалистичные числовые данные.''',
    Discipline.philosophy: '''ДИСЦИПЛИНА: философия.
Глаголы Bloom-Apply: примени (кантианскую категорию к случаю, утилитаристский принцип), классифицируй (философа по направлению, текст по школе).
Глаголы Bloom-Analyze: сравни (Платона с Аристотелем, Юма с Кантом), различи (деонтологическую этику от консеквенциалистской), аргументируй, опираясь на источник.
Глаголы Bloom-Evaluate: критикуй тезис, оцени когерентность системы, построй контраргумент.
Примеры: дилемма вагонетки, парадокс лжеца, проблема разума и тела.''',
    Discipline.history: '''ДИСЦИПЛИНА: история.
Глаголы Bloom-Apply: датировать событие правильно, применять (категорию периодизации к факту), определять (непосредственную и отдаленную причины).
Глаголы Bloom-Analyze: различать (экономические/политические/социальные причины), сравнивать (Французскую и Американскую революции), интерпретировать первичный источник, выявлять предвзятость.
Глаголы Bloom-Evaluate: оценивать влияние события, критиковать историографический тезис, аргументировать на основе документальных свидетельств.
Избегайте сухих дат: спрашивайте ПОЧЕМУ + КАК, а не только КОГДА.''',
    Discipline.generic: '''ДИСЦИПЛИНА: общая.
Глаголы Bloom-Apply: применять, вычислять, предсказывать, классифицировать.
Глаголы Bloom-Analyze: различать, сравнивать, интерпретировать, выводить.
Глаголы Bloom-Evaluate: оценивать, критиковать, аргументировать, обосновывать.
Без конкретного домена, отдавайте предпочтение вопросам, требующим многошагового рассуждения и решаемым по материалам кластера.
Избегайте общих вопросов типа "Что такое X?" (Remember-only).''',
  },
  'nl': {
    Discipline.physics: '''DISCIPLINE: natuurkunde.
Werkwoorden Bloom-Apply: bereken (nettokracht, moment, energie), voorspel (baan, positie t+Δt), pas toe (Newton II, behoud).
Werkwoorden Bloom-Analyze: leid af (bewegingsvergelijking), onderscheid (elastisch/inelastisch), vergelijk (inertiële vs niet-inertiële stelsels).
Werkwoorden Bloom-Evaluate: evalueer de stabiliteit van een systeem, bekritiseer een modelhypothese.
Voorkeursscenario's: hellend vlak met wrijving, 1D/2D botsingen, harmonische oscillator, RLC-circuits, thermodynamica van de Carnot-cyclus.''',
    Discipline.math: '''DISCIPLINE: wiskunde.
Werkwoorden Bloom-Apply: los op (vergelijking, stelsel), bereken (limiet,
afgeleide, partiële integratie/substitutie), pas toe (regel van
de l'Hôpital, stelling van Lagrange).
Werkwoorden Bloom-Analyze: bewijs (door inductie, uit het ongerijmde, door contrapositie),
vind een tegenvoorbeeld, toon de equivalentie aan, classificeer de discontinuïteiten.
Werkwoorden Bloom-Evaluate: bekritiseer een bewijs, evalueer de algemeenheid
van een stelling.
Nooit alleen "bereken" als enig werkwoord — examenwiskunde is een toets.''',
    Discipline.chemistry: '''DISCIPLINE: chemie.
Werkwoorden Bloom-Apply: balanceer (redoxreactie, neutralisatie), bereken (molariteit, pH, concentratie), voorspel (reactieproduct).
Werkwoorden Bloom-Analyze: onderscheid (sterk/zwak zuur, SN1/SN2), verklaar het moleculaire mechanisme, classificeer verbindingen per functionele groep.
Werkwoorden Bloom-Evaluate: evalueer de thermodynamische spontaniteit (ΔG), bekritiseer een syntheseroute.
Zoek ALTIJD naar moleculaire causaliteit en het representatieniveau (moleculair/macroscopisch/symbolisch).''',
    Discipline.biology: '''DISCIPLINE: biologie.
Werkwoorden Bloom-Apply: pas toe (Hardy-Weinberg, wetten van Mendel), voorspel (F2-fenotypes, uitkomst mutatie), bereken (allelfrequenties).
Werkwoorden Bloom-Analyze: onderscheid (mitose/meiose, prokaryoten/eukaryoten), leg uit de functie van (organel, systeem), vergelijk (natuurlijke selectie vs genetische drift).
Werkwoorden Bloom-Evaluate: evalueer het bewijs voor een evolutionaire hypothese, bekritiseer een experimenteel model.
Voorbeelden: ATP-synthase, genregulatie, homeostase, ecosystemen.''',
    Discipline.medicine: '''DISCIPLINE: geneeskunde.
Werkwoorden Bloom-Apply: diagnosticeer (op basis van symptomen/tekenen), stel voor (eerstelijnsbehandeling), pas toe (DSM-criteria, ESC-richtlijnen).
Werkwoorden Bloom-Analyze: onderscheid (differentiaaldiagnose), interpreteer (laboratoriumonderzoeken, beeldvorming), evalueer de onderliggende fysiopathologie.
Werkwoorden Bloom-Evaluate: bekritiseer een behandeling, evalueer de prognose, redeneer op basis van bewijs (RCT vs casusrapport).
Concrete klinische scenario's met anamnese + onderzoeken + verwachte prognose.''',
    Discipline.law: '''DISCIPLINE: recht.
Werkwoorden Bloom-Apply: pas toe (norm op het concrete geval), kwalificeer
(juridisch feitencomplex), stel vast (aansprakelijkheid).
Werkwoorden Bloom-Analyze: onderscheid (opzet/schuld, overeenkomst/eenzijdige rechtshandeling),
vergelijk (jurisprudentie), beargumenteer vanuit de ratio legis.
Werkwoorden Bloom-Evaluate: beoordeel de rechtmatigheid van een handeling, bekritiseer
een jurisprudentiële interpretatie.
Voorkeursscenario's: concrete casussen met duidelijke feitencomplexen +
toepasselijke normen (Burgerlijk Wetboek, Wetboek van Strafrecht, Grondwet).''',
    Discipline.economics: '''DISCIPLINE: economie.
Werkwoorden Bloom-Apply: bereken (elasticiteit, BBP, surplus), pas toe (model van perfecte concurrentie, IS-LM), voorspel het effect van een monetair/fiscaal beleid.
Werkwoorden Bloom-Analyze: onderscheid (substitutie-effect vs inkomenseffect), vergelijk (marktregimes), interpreteer macro-economische gegevens.
Werkwoorden Bloom-Evaluate: evalueer een economisch beleid, bekritiseer een aanname van een model (perfecte mobiliteit, rationaliteit).
Voorbeelden met vraag- en aanbodgrafieken + realistische numerieke gegevens.''',
    Discipline.philosophy: '''DISCIPLINE: filosofie.
Werkwoorden Bloom-Apply: pas toe (Kantiaanse categorie op een geval, utilitaristisch principe), classificeer (filosoof per stroming, tekst per school).
Werkwoorden Bloom-Analyze: vergelijk (Plato vs Aristoteles, Hume vs Kant), onderscheid (deontologische ethiek vs consequentialistische ethiek), argumenteer vanuit de bron.
Werkwoorden Bloom-Evaluate: bekritiseer een stelling, evalueer de interne consistentie van een systeem, bouw een tegenargument op.
Voorbeelden: trolleyprobleem, leugenaarsparadox, lichaam-geestprobleem.''',
    Discipline.history: '''DISCIPLINE: geschiedenis.
Werkwoorden Bloom-Apply: plaats een gebeurtenis correct, pas een periodiserende categorie toe op een feit, localiseer (directe oorzaak vs. indirecte oorzaak).
Werkwoorden Bloom-Analyze: onderscheid (economische/politieke/sociale oorzaken), vergelijk (Franse vs. Amerikaanse Revolutie), interpreteer een primaire bron, identificeer bias.
Werkwoorden Bloom-Evaluate: evalueer de impact van een gebeurtenis, bekritiseer een historiografische these, argumenteer op basis van documentair bewijs.
Vermijd kale data: vraag WAAROM + HOE, niet alleen WANNEER.''',
    Discipline.generic: '''DISCIPLINE: algemeen.
Werkwoorden Bloom-Apply: pas toe, bereken, voorspel, classificeer.
Werkwoorden Bloom-Analyze: onderscheid, vergelijk, interpreteer, leid af.
Werkwoorden Bloom-Evaluate: evalueer, bekritiseer, argumenteer, rechtvaardig.
Zonder specifiek domein, geef de voorkeur aan vragen die meerstapredenering vereisen en die oplosbaar zijn met behulp van de aantekeningen van het cluster.
Vermijd generieke vragen zoals "Wat is X?" (Alleen onthouden).''',
  },
  'sv': {
    Discipline.physics: '''ÄMNE: fysik.
Verb Bloom-Apply: beräkna (nettokraft, vridmoment, energi), förutsäg (bana, position vid t+Δt), tillämpa (Newtons andra lag, bevarandelagar).
Verb Bloom-Analyze: härled (rörelseekvation), skilj mellan (elastisk/oelastisk), jämför (inertialsystem kontra icke-inertialsystem).
Verb Bloom-Evaluate: utvärdera ett systems stabilitet, kritisera en modellhypotes.
Föredragna scenarier: lutande plan med friktion, stötar i 1D/2D, harmonisk oscillator, RLC-kretsar, termodynamik för Carnotcykeln.''',
    Discipline.math: '''ÄMNE: matematik.
Verb Bloom-Apply: lösa (ekvation, system), beräkna (gränsvärde, derivata, integral med partiell integration/substitution), tillämpa (de l'Hôpitals regel, Lagranges sats).
Verb Bloom-Analyze: bevisa (med induktion, motsägelsebevis, kontrapositivt), hitta ett motexempel, visa ekvivalensen, klassificera diskontinuiteter.
Verb Bloom-Evaluate: kritisera ett bevis, utvärdera generaliteten hos en sats.
Aldrig bara "beräkna" som enda verb — examensmatematik är ett prov.''',
    Discipline.chemistry: '''ÄMNE: kemi.
Verb Bloom-Apply: balansera (redoxreaktion, neutralisation), beräkna (molaritet, pH, koncentration), förutsäg (reaktionsprodukt).
Verb Bloom-Analyze: skilj mellan (stark/svag syra, SN1/SN2), förklara den molekylära mekanismen, klassificera föreningar efter funktionell grupp.
Verb Bloom-Evaluate: utvärdera den termodynamiska spontaniteten (ΔG), kritisera en syntesväg.
Sök ALLTID efter molekylär kausalitet och representationsnivån (molekylär/makroskopisk/symbolisk).''',
    Discipline.biology: '''DISCIPLIN: biologi.
Verb Bloom-Apply: tillämpa (Hardy-Weinberg, Mendels lagar), förutsäga (F2-fenotyper, mutationsutfall), beräkna (allelfrekvenser).
Verb Bloom-Analyze: skilja mellan (mitos/meios, prokaryoter/eukaryoter), förklara funktionen (organell, system), jämföra (naturligt urval vs genetisk drift).
Verb Bloom-Evaluate: utvärdera bevis för en evolutionär hypotes, kritisera en experimentell modell.
Exempel: ATP-syntas, genreglering, homeostas, ekosystem.''',
    Discipline.medicine: '''ÄMNE: medicin.
Verb Bloom-Apply: diagnostisera (baserat på symtom/tecken), föreslå (förstahandsbehandling), tillämpa (DSM-kriterier, ESC-riktlinjer).
Verb Bloom-Analyze: skilja mellan (differentialdiagnos), tolka (laboratorieprover, bilddiagnostik), bedöma den underliggande patofysiologin.
Verb Bloom-Evaluate: kritisera en behandling, bedöma prognosen, resonera kring evidens (RCT vs fallrapport).
Konkreta kliniska scenarier med anamnes + undersökningar + förväntad prognos.''',
    Discipline.law: '''ÄMNESOMRÅDE: juridik.
Verb Bloom-Apply: tillämpar (norm till konkret fall), kvalificerar (rättsförhållande), identifierar (ansvar).
Verb Bloom-Analyze: skiljer mellan (uppsåt/oaktsamhet, avtal/ensidig rättshandling), jämför (rättspraxis), argumenterar utifrån lagens syfte.
Verb Bloom-Evaluate: bedömer en rättsakts laglighet, kritiserar en rättslig tolkning.
Föredragna scenarier: konkreta fall med tydliga rekvisit + tillämpliga normer (civilrättslig lagstiftning, straffrättslig lagstiftning, grundlagar).''',
    Discipline.economics: '''ÄMNE: ekonomi.
Verb Bloom-Apply: beräkna (elasticitet, BNP, överskott), tillämpa
(modell för perfekt konkurrens, IS-LM), förutsäga effekten av en
penning-/finanspolitik.
Verb Bloom-Analyze: skilja mellan (substitutionseffekt kontra inkomsteffekt),
jämföra (marknadsregimer), tolka makroekonomiska data.
Verb Bloom-Evaluate: utvärdera en ekonomisk politik, kritisera ett
antagande i en modell (perfekt mobilitet, rationalitet).
Exempel med utbuds- och efterfrågediagram + realistiska numeriska data.''',
    Discipline.philosophy: '''ÄMNE: filosofi.
Verb Bloom-Apply: tillämpa (en kantiansk kategori på ett fall, en utilitaristisk princip), klassificera (filosof efter strömning, text efter skola).
Verb Bloom-Analyze: jämföra (Platon mot Aristoteles, Hume mot Kant), skilja mellan (deontologisk mot konsekventialistisk etik), argumentera utifrån källan.
Verb Bloom-Evaluate: kritisera en tes, värdera ett systems interna koherens, konstruera en motargumentation.
Exempel: trolleyproblemet, lögnarparadoxen, kropp-själ-problemet.''',
    Discipline.history: '''ÄMNE: historia.
Verb Bloom-Apply: datera korrekt en händelse, tillämpa (en periodiserande kategori på ett faktum), lokalisera (närliggande orsak vs avlägsen orsak).
Verb Bloom-Analyze: skilja mellan (ekonomiska/politiska/sociala orsaker), jämföra (franska revolutionen vs amerikanska), tolka en primärkälla, identifiera partiskhet.
Verb Bloom-Evaluate: värdera en händelses inverkan, kritisera en historiografisk tes, argumentera utifrån dokumentär bevisning.
Undvik sterila datum: fråga VARFÖR + HUR, inte bara NÄR.''',
    Discipline.generic: '''ÄMNE: generisk.
Verb Bloom-Apply: tillämpa, beräkna, förutsäga, klassificera.
Verb Bloom-Analyze: urskilja, jämföra, tolka, härleda.
Verb Bloom-Evaluate: utvärdera, kritisera, argumentera, motivera.
Utan specifik domän, prioritera frågor som kräver flerstegsresonemang och som kan lösas från klustrets anteckningar.
Undvik generiska frågor som "Vad är X?" (Remember-only).''',
  },
  'pl': {
    Discipline.physics: '''DYSCYPLINA: fizyka.
Czasowniki Bloom-Apply: oblicz (siłę wypadkową, moment, energię), przewiduj (trajektorię, położenie w czasie t+Δt), zastosuj (II zasadę Newtona, zasady zachowania).
Czasowniki Bloom-Analyze: wyprowadź (równanie ruchu), rozróżnij (zderzenia sprężyste/niesprężyste), porównaj (układy inercjalne vs nieinercjalne).
Czasowniki Bloom-Evaluate: oceń stabilność systemu, skrytykuj hipotezę modelu.
Preferowane scenariusze: równia pochyła z tarciem, zderzenia 1D/2D, oscylator harmoniczny, obwody RLC, termodynamika cyklu Carnota.''',
    Discipline.math: '''DYSCYPLINA: matematyka.
Czasowniki Bloom-Apply: rozwiąż (równanie, układ równań), oblicz (granicę, pochodną, całkę przez części/przez podstawienie), zastosuj (regułę de l'Hôpitala, twierdzenie Lagrange'a).
Czasowniki Bloom-Analyze: udowodnij (przez indukcję, przez sprzeczność, przez kontrapozycję), znajdź kontrprzykład, pokaż równoważność, sklasyfikuj nieciągłości.
Czasowniki Bloom-Evaluate: skrytykuj dowód, oceń ogólność twierdzenia.
Nigdy samo "oblicz" jako jedyny czasownik — matematyka egzaminacyjna to sprawdzian.''',
    Discipline.chemistry: '''DYSCYPLINA: chemia.
Czasowniki Bloom-Apply: zbilansuj (reakcja redoks, neutralizacja), oblicz (stężenie molowe, pH, stężenie), przewiduj (produkt reakcji).
Czasowniki Bloom-Analyze: rozróżnij (kwas mocny/słaby, SN1/SN2), wyjaśnij mechanizm molekularny, klasyfikuj związki według grupy funkcyjnej.
Czasowniki Bloom-Evaluate: oceń spontaniczność termodynamiczną (ΔG), skrytykuj drogę syntezy.
Zawsze szukaj przyczynowości molekularnej i poziomu reprezentacji (molekularny/makroskopowy/symboliczny).''',
    Discipline.biology: '''DYSCYPLINA: biologia.
Czasowniki Bloom-Apply: zastosuj (Hardy-Weinberg, prawa Mendla), przewiduj
(fenotypy F2, wynik mutacji), oblicz (częstotliwości alleli).
Czasowniki Bloom-Analyze: rozróżnij (mitozę/mejozę, prokarioty/eukarioty),
wyjaśnij funkcję (organellum, systemu), porównaj (selekcję
naturalną vs dryf genetyczny).
Czasowniki Bloom-Evaluate: oceń dowody hipotezy ewolucyjnej,
skrytykuj model eksperymentalny.
Przykłady: syntaza ATP, regulacja genów, homeostaza, ekosystemy.''',
    Discipline.medicine: '''DYSCYPLINA: medycyna.
Czasowniki Bloom-Apply: diagnozuj (na podstawie objawów/oznak), proponuj (terapię pierwszego rzutu), stosuj (kryteria DSM, wytyczne ESC).
Czasowniki Bloom-Analyze: rozróżniaj (diagnostyka różnicowa), interpretuj (wyniki badań laboratoryjnych, obrazowanie), oceniaj leżącą u podstaw fizjopatologię.
Czasowniki Bloom-Evaluate: krytykuj leczenie, oceniaj rokowanie, argumentuj na podstawie dowodów (RCT vs opis przypadku).
Konkretne scenariusze kliniczne z wywiadem + badaniami + przewidywanym rokowaniem.''',
    Discipline.law: '''DYSCYPLINA: prawo.
Czasowniki Bloom-Apply: stosuje (normę do konkretnego przypadku), kwalifikuje (stan faktyczny), ustala (odpowiedzialność).
Czasowniki Bloom-Analyze: rozróżnia (umyślność/nieumyślność, umowę/czynność jednostronną), porównuje (orzecznictwo), argumentuje z ratio legis.
Czasowniki Bloom-Evaluate: ocenia legalność aktu, krytykuje interpretację orzecznictwa.
Preferowane scenariusze: konkretne przypadki z jasnymi elementami stanu faktycznego + normy mające zastosowanie (kodeks cywilny, karny, konstytucja).''',
    Discipline.economics: '''DYSCYPLINA: ekonomia.
Czasowniki Bloom-Apply: oblicz (elastyczność, PKB, nadwyżka), zastosuj (model konkurencji doskonałej, IS-LM), przewiduj efekt polityki monetarnej/fiskalnej.
Czasowniki Bloom-Analyze: rozróżnij (efekt substytucyjny vs dochodowy), porównaj (reżimy rynkowe), interpretuj dane makroekonomiczne.
Czasowniki Bloom-Evaluate: oceń politykę gospodarczą, krytykuj założenie modelu (doskonała mobilność, racjonalność).
Przykłady z wykresami popytu i podaży + realistycznymi danymi liczbowymi.''',
    Discipline.philosophy: '''DYSCYPLINA: filozofia.
Czasowniki Bloom-Apply: zastosuj (kategorię kantowską do przypadku, zasadę utylitarystyczną), klasyfikuj (filozofa według nurtu, tekst według szkoły).
Czasowniki Bloom-Analyze: porównaj (Platona z Arystotelesem, Hume'a z Kantem), rozróżnij (etykę deontologiczną od konsekwencjalistycznej), argumentuj na podstawie źródła.
Czasowniki Bloom-Evaluate: skrytykuj tezę, oceń wewnętrzną spójność systemu, zbuduj kontrargumentację.
Przykłady: dylemat wagonika, paradoks kłamcy, problem umysł-ciało.''',
    Discipline.history: '''DYSCYPLINA: historia.
Czasowniki Bloom-Apply: poprawnie datuje wydarzenie, stosuje (kategorię periodyzacyjną do faktu), lokalizuje (przyczynę bezpośrednią vs przyczynę odległą).
Czasowniki Bloom-Analyze: rozróżnia (przyczyny ekonomiczne/polityczne/społeczne), porównuje (Rewolucję Francuską vs Amerykańską), interpretuje źródło pierwotne, identyfikuje stronniczość.
Czasowniki Bloom-Evaluate: ocenia wpływ wydarzenia, krytykuje tezę historiograficzną, argumentuje na podstawie dowodów dokumentalnych.
Unikaj jałowych dat: pytaj DLACZEGO + JAK, nie tylko KIEDY.''',
    Discipline.generic: '''DYSCYPLINA: ogólna.
Czasowniki Bloom-Apply: stosuj, oblicz, przewiduj, klasyfikuj.
Czasowniki Bloom-Analyze: rozróżnij, porównaj, interpretuj, wyprowadź.
Czasowniki Bloom-Evaluate: oceń, krytykuj, argumentuj, uzasadnij.
Bez specyficznej dziedziny, preferuj pytania wymagające wieloetapowego rozumowania i możliwe do rozwiązania na podstawie notatek z klastra.
Unikaj ogólnych pytań typu „Co to jest X?” (tylko zapamiętywanie).''',
  },
  'tr': {
    Discipline.physics: '''DİSİPLİN: fizik.
Fiilleri Bloom-Apply: hesapla (net kuvvet, momentum, enerji), tahmin et (yörünge, t+Δt konumu), uygula (Newton II, korunum).
Fiilleri Bloom-Analyze: türet (hareket denklemi), ayırt et (esnek/esnek olmayan), karşılaştır (eylemsiz vs eylemsiz olmayan sistemler).
Fiilleri Bloom-Evaluate: bir sistemin kararlılığını değerlendir, bir model hipotezini eleştir.
Tercih edilen senaryolar: sürtünmeli eğik düzlem, 1B/2B çarpışmalar, harmonik osilatör, RLC devreleri, Carnot çevrimi termodinamiği.''',
    Discipline.math: '''DİSİPLİN: matematik.
Bloom-Apply Fiilleri: çöz (denklem, sistem), hesapla (limit, türev, kısmi integrasyon/yerine koyma ile integral), uygula (de l'Hôpital kuralı, Lagrange teoremi).
Bloom-Analyze Fiilleri: kanıtla (tümevarım ile, çelişki ile, karşıt-ters ile), bir karşı örnek bul, eşdeğerliği göster, süreksizlikleri sınıflandır.
Bloom-Evaluate Fiilleri: bir kanıtı eleştir, bir teoremin genelliğini değerlendir.
Sadece "hesapla" tek fiil olarak asla kullanılmamalıdır — sınav matematiği bir ispattır.''',
    Discipline.chemistry: '''DİSİPLİN: kimya.
Fiiller Bloom-Apply: dengele (redoks reaksiyonu, nötralizasyon), hesapla (molarite, pH, konsantrasyon), tahmin et (reaksiyon ürünü).
Fiiller Bloom-Analyze: ayırt et (kuvvetli/zayıf asit, SN1/SN2), moleküler mekanizmayı açıkla, bileşikleri fonksiyonel gruba göre sınıflandır.
Fiiller Bloom-Evaluate: termodinamik kendiliğindenliği değerlendir (ΔG), bir sentez yolunu eleştir.
HER ZAMAN moleküler nedenselliği ve temsil düzeyini (moleküler/makroskopik/sembolik) ara.''',
    Discipline.biology: '''DİSİPLİN: biyoloji.
Fiiller Bloom-Apply: uygula (Hardy-Weinberg, Mendel yasaları), tahmin et (F2 fenotipleri, mutasyon sonucu), hesapla (alel frekansları).
Fiiller Bloom-Analyze: ayırt et (mitoz/mayoz, prokaryotlar/ökaryotlar), işlevini açıkla (organel, sistem), karşılaştır (doğal seçilim vs genetik sürüklenme).
Fiiller Bloom-Evaluate: değerlendir (bir evrimsel hipotezin kanıtlarını), eleştir (deneysel bir modeli).
Örnekler: ATP-sentaz, gen regülasyonu, homeostazi, ekosistemler.''',
    Discipline.medicine: '''DİSİPLİN: tıp.
Fiiller Bloom-Apply: teşhis et (belirti/bulgulara göre), öner (birinci basamak tedavi), uygula (DSM kriterleri, ESC kılavuzları).
Fiiller Bloom-Analyze: ayırt et (ayırıcı tanı), yorumla (laboratuvar testleri, görüntüleme), altta yatan fizyopatolojiyi değerlendir.
Fiiller Bloom-Evaluate: bir tedaviyi eleştir, prognozu değerlendir, kanıtlar üzerine muhakeme et (RKÇ vs vaka sunumu).
Anamnez + testler + beklenen prognoz içeren somut klinik senaryolar.''',
    Discipline.law: '''DİSİPLİN: hukuk.
Bloom-Uygulama Fiilleri: uygula (normu somut olaya), nitelendir (hukuki olayı), belirle (sorumluluğu).
Bloom-Analiz Fiilleri: ayırt et (kast/kusur, sözleşme/tek taraflı işlem), karşılaştır (içtihatları), kanunun ruhundan argüman geliştir.
Bloom-Değerlendirme Fiilleri: değerlendir (bir işlemin hukuka uygunluğunu), eleştir (bir içtihat yorumunu).
Tercih Edilen Senaryolar: açık hukuki olay unsurları içeren somut vakalar + uygulanabilir normlar (Medeni Kanun, Ceza Kanunu, Anayasa).''',
    Discipline.economics: '''DİSİPLİN: ekonomi.
Bloom-Uygulama Fiilleri: hesapla (esneklik, GSYİH, refah fazlası), uygula (tam rekabet modeli, IS-LM), para/maliye politikasının etkisini tahmin et.
Bloom-Analiz Fiilleri: ayırt et (ikame etkisi ile gelir etkisi), karşılaştır (piyasa rejimleri), makroekonomik verileri yorumla.
Bloom-Değerlendirme Fiilleri: ekonomi politikasını değerlendir, bir modelin varsayımını eleştir (mükemmel hareketlilik, rasyonellik).
Talep-arz grafikleri + gerçekçi sayısal verilerle örnekler.''',
    Discipline.philosophy: '''DİSİPLİN: felsefe.
Fiiller Bloom-Apply: uygula (Kantçı bir kategoriyi bir duruma, faydacı ilkeyi), sınıflandır (filozofu akımına göre, metni ekolüne göre).
Fiiller Bloom-Analyze: karşılaştır (Platon ile Aristoteles'i, Hume ile Kant'ı), ayırt et (deontolojik etik ile sonuççu etiği), kaynaktan yola çıkarak argüman sun.
Fiiller Bloom-Evaluate: bir tezi eleştir, bir sistemin iç tutarlılığını değerlendir, bir karşı argüman oluştur.
Örnekler: tramvay ikilemi, yalancı paradoksu, zihin-beden problemi.''',
    Discipline.history: '''DİSİPLİN: tarih.
Fiiller Bloom-Apply: bir olayı doğru tarihlendirme, (bir olaya) dönemselleştirme kategorisi uygulama, (yakın neden ile uzak nedeni) ayırt etme.
Fiiller Bloom-Analyze: (ekonomik/politik/sosyal) nedenleri ayırt etme, (Fransız Devrimi ile Amerikan Devrimi'ni) karşılaştırma, birincil bir kaynağı yorumlama, önyargıyı tespit etme.
Fiiller Bloom-Evaluate: bir olayın etkisini değerlendirme, tarih yazımıyla ilgili bir tezi eleştirme, belgesel kanıtlardan yola çıkarak argüman geliştirme.
Salt tarihlerden kaçının: sadece NE ZAMAN değil, NEDEN + NASIL sorularını sorun.''',
    Discipline.generic: '''DİSİPLİN: genel.
Bloom-Apply Fiilleri: uygula, hesapla, tahmin et, sınıflandır.
Bloom-Analyze Fiilleri: ayırt et, karşılaştır, yorumla, türet.
Bloom-Evaluate Fiilleri: değerlendir, eleştir, savun, gerekçelendir.
Özel bir alan olmaksızın, çok adımlı akıl yürütme gerektiren ve küme notlarından çözülebilecek soruları tercih et.
"X nedir?" gibi genel sorulardan kaçın (Sadece Hatırlama).''',
  },
};

String? bootstrapExamDisciplineHintsFor(
        Discipline discipline, String langCode) =>
    _bootstrapExamDisciplineHints[langCode]?[discipline];
