// ============================================================================
// 🌍 ExamDisciplineHintsBootstrap — AI-translated Exam discipline hints
// for the 14 Tier-1/2 bootstrap languages.
//
// Generated by `tool/bootstrap_exam_discipline_hints.dart` (run-on-demand).
// Source-of-truth: the IT cells in `discipline_hints_exam_it.dart`.
//
// Status: `ai_bootstrap` per docs/socratic_native_validation_protocol.md.
//
// PLACEHOLDER: this file is the scaffold that compiles before the first
// bootstrap run. Map is empty → `bootstrapExamDisciplineHintsFor`
// returns null → `ExamPedagogyRegistry.disciplineHintsFor` falls back
// to the EN module. Running the tool will overwrite this file with
// the 14-language translation map.
// ============================================================================

import '../../../canvas/ai/socratic/socratic_discipline.dart';

const Map<String, Map<Discipline, String>> _bootstrapExamDisciplineHints = {};

/// Returns the AI-translated discipline hint for [discipline] in
/// [langCode], or null when not available. Caller (
/// `ExamPedagogyRegistry`) falls back to the EN module.
String? bootstrapExamDisciplineHintsFor(
        Discipline discipline, String langCode) =>
    _bootstrapExamDisciplineHints[langCode]?[discipline];
