#!/usr/bin/env python3
"""
Safe Italian → English translator for Dart code comments.
Only replaces multi-word Italian phrases (safe from code corruption).
Uses exact string matching on comment text portions only.
"""
import os
import re

BASE = '/home/lorenzo/development/nebula_engine'

# ─── SAFE multi-word phrases & full sentences ───
# These are safe because they won't appear in code identifiers.
# Ordered from longest to shortest.
PHRASES = sorted([
    # ════ Full sentences / long phrases ════
    ("in coordinate canvas", "in canvas coordinates"),
    ("in coordinate schermo", "in screen coordinates"),
    ("in coordinate locali", "in local coordinates"),
    ("coordinate canvas", "canvas coordinates"),
    ("coordinate schermo", "screen coordinates"),
    ("coordinate locali", "local coordinates"),
    ("del tile", "of the tile"),
    ("dei tile", "of the tiles"),
    ("on the canvas", "on the canvas"),
    ("non dovrebbe mai succedere", "should never happen"),
    ("sono i valori di default", "are the default values"),
    ("stiamo disegnando attivamente", "we are actively drawing"),
    ("non ancora completato", "not yet completed"),
    ("non ancora iniziati", "not yet started"),
    ("non ancora disegnati", "not yet drawn"),
    ("non ancora disegnato", "not yet drawn"),
    ("già completati", "already completed"),
    ("già completato", "already completed"),
    ("sotto il dito", "under the finger"),
    ("sotto il cursore", "under the cursor"),
    ("in mode editing", "in editing mode"),
    ("in un unico path", "in a single path"),
    ("ad ogni punto", "at each point"),
    ("ad ogni frame", "at each frame"),
    ("ogni millisecondo conta", "every millisecond counts"),
    ("ogni altra pagina", "every other page"),
    ("per mantenere aggiornato", "to keep updated"),
    ("per mantenerli", "to keep them"),
    ("mantenendo le posizioni", "while maintaining positions"),
    ("con cautela", "with caution"),
    ("con bordo blu", "with blue border"),
    ("per massimizzare canvas", "to maximize canvas"),
    ("per calcolare variazione scala", "to calculate scale variation"),
    ("per preservare identità dopo restore", "to preserve identity after restore"),
    ("per append atomico", "for atomic append"),
    ("per performance O(1)", "for O(1) performance"),
    ("dopo prima chiamata", "after first call"),
    ("dopo che lo stroke was aggiunto", "after the stroke was added"),
    ("dopo rotazione", "after rotation"),
    ("dopo l'eliminazione", "after deletion"),
    ("prima di operazioni distruttive", "before destructive operations"),
    ("prima versione taggata", "first tagged version"),
    ("per iniziare drag", "to start drag"),
    ("per non disturbare", "to not disturb"),
    ("per molti strokes", "for many strokes"),
    ("per caricare punti", "to load points"),
    ("per salvare stato", "to save state"),
    ("per salvataggio canvas", "for canvas saving"),
    ("per salvataggio", "for saving"),
    ("per ottimizzare storage", "to optimize storage"),
    ("per ottimizzare", "to optimize"),
    ("per mascherare il tratto", "to mask the stroke"),
    ("per rimanere sul segmento", "to stay on the segment"),
    ("per l'esportazione timelapse", "for timelapse export"),
    ("per l'esportazione", "for export"),
    ("per l'export multi-pagina", "for multi-page export"),
    ("per i pannelli", "for panels"),
    ("per l'intero tratto", "for the entire stroke"),
    ("per operazioni guide", "for guide operations"),
    ("per caricare", "to load"),
    ("per aggiungere", "to add"),
    ("per notificare", "to notify"),
    ("per distinguerli", "to distinguish them"),
    ("per filtrare", "to filter"),
    ("per evitare", "to avoid"),
    ("per tracciare", "to track"),
    ("per riutilizzo", "for reuse"),
    ("per calcolare", "to calculate"),
    ("per eliminare", "to eliminate"),
    ("per iniziare", "to start"),
    ("per mascherare", "to mask"),
    ("per rimanere", "to remain"),
    ("per assicurare", "to ensure"),
    ("per variare", "to vary"),
    ("per capire dove", "to understand where"),
    ("per account variazioni", "to account for variations"),
    ("per multi-pagina", "for multi-page"),
    ("appare al long press", "appears on long press"),
    ("non ricalcola tutto", "doesn't recalculate everything"),
    ("sotto pressione memoria", "under memory pressure"),
    ("a zoom estremi", "at extreme zoom levels"),
    ("percorso del lasso", "lasso path"),
    ("elementi immagine", "image elements"),
    ("elementi testo", "text elements"),
    ("elementi di testo", "text elements"),
    ("la shape corrente", "the current shape"),
    ("la shape abbia", "the shape has"),
    ("le shape geometriche", "the geometric shapes"),
    ("shape corrente", "current shape"),
    ("shape geometriche", "geometric shapes"),
    ("elemento di testo", "text element"),
    ("elemento selezionato", "selected element"),
    ("elemento immagine", "image element"),
    ("elemento testo", "text element"),
    ("immagine di sfondo", "background image"),
    ("immagine selezionata", "selected image"),
    ("completamente visibile", "completely visible"),
    ("stroke in-progress", "in-progress stroke"),
    ("tratto sull'immagine", "stroke on the image"),
    ("pointer attivo", "active pointer"),
    ("registrazione ha tratti", "recording has strokes"),
    ("finisce con punteggiatura", "ends with punctuation"),
    ("la cache copre", "the cache covers"),
    ("is ancora dentro", "is still inside"),
    ("dentro l'area", "inside the area"),
    ("centro della shape", "center of the shape"),
    ("prossima sessione", "next session"),
    ("lasso e seleziona", "lasso and selects"),
    ("lasso ora che", "lasso now that"),
    ("mode stylus", "stylus mode"),
    ("focal point iniziale fisso", "initial focal point fixed"),
    ("punti chiave della shape", "key points of the shape"),
    ("direzioni aumentano", "directions increase"),
    ("direzione del disegno", "drawing direction"),
    ("stato di playback", "playback state"),
    ("stato del disegno", "drawing state"),
    ("stato dell'engine", "engine state"),
    ("stato interno", "internal state"),
    ("posizione effettiva della pagina", "actual page position"),
    ("indicatore funzioni anche", "indicator works even"),
    ("drag (sposta elementi)", "drag (moves elements)"),
    ("drag dell'elemento", "drag of the element"),
    ("la configurazione cambia", "the configuration changes"),
    ("configurazione cambia", "configuration changes"),
    ("canvas cambia durante il replay", "canvas changes during replay"),
    ("aggiunta di uno stroke esterno", "addition of an external stroke"),
    ("area di selezione", "selection area"),
    ("pulsante layer", "layer button"),
    ("pannello opaco", "opaque panel"),
    ("guide salvate", "saved guides"),
    ("pannello layer", "layer panel"),
    ("punto of the stroke is dentro il raggio della gomma", "point of the stroke is within the eraser radius"),
    ("punto tocca questo testo", "point touches this text"),
    ("punto of the stroke is dentro il path", "point of the stroke is inside the path"),
    ("punto of the stroke is nel path", "point of the stroke is in the path"),
    ("tile specifico is dirty", "specific tile is dirty"),
    ("un singolo Paint", "a single Paint"),
    ("effetto realistico dove:", "realistic effect where:"),
    ("effetto realistico", "realistic effect"),
    ("unico path", "single path"),
    ("tratti registrati mentre", "recorded strokes while"),
    ("~30% di storage per sessioni con molte cancellazioni", "~30% of storage for sessions with many deletions"),
    ("fix assicura che", "fix ensures that"),
    ("crea un effetto realistico", "creates a realistic effect"),
    ("is called da NebulaLayerController quando serve", "is called by NebulaLayerController when needed"),
    ("more efficiente di updateDrag because non ricalcola tutto", "more efficient than updateDrag because it doesn't recalculate everything"),
    ("dal pulsante dedicato nella toolbar", "by the dedicated toolbar button"),
    ("basandosi sui bounds degli stroke e shapes visibili", "based on visible stroke and shape bounds"),
    ("bounds di una specific page", "bounds of a specific page"),
    ("cathat is valida for the number of tratti dato", "cache is valid for the given number of strokes"),
    ("plugin nativo is available su questa piattaforma", "native plugin is available on this platform"),
    ("aggiungendo nuovi tratti alla cache esistente", "by adding new strokes to the existing cache"),
    ("selezione dopo", "selection after"),
    ("stato e notifica listener", "state and notifies listeners"),
    ("tutte le pagine with the nuova size", "all pages with the new size"),
    ("16ms (~60fps) per animazione fluida", "16ms (~60fps) for smooth animation"),
    ("ogni 16ms (~60fps)", "every 16ms (~60fps)"),
    ("per animazione fluida", "for smooth animation"),
    ("dialog impostazioni template PDF", "PDF template settings dialog"),
    ("dialog impostazioni", "settings dialog"),
    ("renderizzato sotto usando selectedElement", "rendered below using selectedElement"),
    ("mosamong the tratti registrati", "shows the recorded strokes"),
    ("serializza eventi in UTF-8 JSONL bytes", "serialize events in UTF-8 JSONL bytes"),
    ("se delta tracking is disabled", "if delta tracking is disabled"),
    ("usa sempre lo stesso", "always use the same"),
    ("Ricalcola bounds", "Recalculate bounds"),
    ("Serializza eventi", "Serialize events"),
    ("Trasforma screen coordinates", "Transform screen coordinates"),
    ("Trasla per posizionare", "Translate to position"),
    ("Trasla al sistema di", "Translate to the coordinate system of"),
    ("Comprime elementData per", "Compresses elementData for"),
    ("Comprimi elementData per", "Compress elementData for"),
    ("Cicla segmenti simmetria", "Cycle symmetry segments"),
    ("Cancella strokes", "Delete strokes"),
    ("Cancella lo stroke", "Cancel the stroke"),
    ("Cancellazione della vibrazione attiva", "Cancel active vibration"),
    ("Cancellazione della vibrazione", "Vibration cancellation"),
    ("Trova e aggiorna", "Find and update"),
    ("Trova la sessione", "Find the session"),
    ("Trova l'elemento", "Find the element"),
    ("Trova l'inizio", "Find the start"),
    ("Trova l'immagine", "Find the image"),
    ("Cambia template", "Change template"),
    ("Combina pressione", "Combine pressure"),
    ("Combina risultati", "Combine results"),
    ("Combina tutti", "Combine all"),
    ("Compensa gli elementi", "Compensate the elements"),
    ("Compensa lo scroll", "Compensate the scroll"),
    ("Clears il tratto", "Clears the stroke"),
    ("Clears stato drag/resize", "Clears drag/resize state"),
    ("Clears tutto (usare con cautela!)", "Clears everything (use with caution!)"),
    ("Clears stato", "Clears state"),
    ("Conferma posizionamento", "Confirm placement"),
    ("Callback chiamato quando serve salvare stato", "Callback called when state needs to be saved"),
    ("Callback chiamato quando", "Callback called when"),
    ("Callback chiamato when", "Callback called when"),
    ("Callback invocato quando punti sono aggiornati", "Callback invoked when points are updated"),
    ("Callback per aggiungere elementi immagine (gestiti separatamente)", "Callback for adding image elements (managed separately)"),
    ("Callback per aggiungere elementi testo (gestiti separatamente)", "Callback for adding text elements (managed separately)"),
    ("Callback per caricare punti da storage", "Callback for loading points from storage"),
    ("Callback per every frame", "Callback for every frame"),
    ("Callback per notificare l'aggiunta di uno stroke esterno", "Callback to notify the addition of an external stroke"),
    ("Callback per notificare when a tile is ready", "Callback to notify when a tile is ready"),
    ("Callbacks da chiamare sotto pressione memoria", "Callbacks to call under memory pressure"),
    ("Callback when the configurazione cambia", "Callback when the configuration changes"),
    ("Callback when the stato di playback cambia", "Callback when the playback state changes"),
    ("Callback when the stato of the canvas cambia durante il replay", "Callback when the canvas state changes during replay"),
    ("Called after the caricamento of the canvas", "Called after the canvas loading"),
    ("Called alla chiusura of the canvas", "Called at the closing of the canvas"),
    ("Called dal pulsante layer nella toolbar", "Called from the layer button in the toolbar"),
    ("Called from the an arrow nel pannello", "Called from an arrow in the panel"),
    ("Called PRIMA di operazioni distruttive", "Called BEFORE destructive operations"),
    ("Carica tutti gli eventi da tutte le sessioni", "Load all events from all sessions"),
    ("Carica guide salvate", "Load saved guides"),
    ("Carica immagine di sfondo se specificata", "Load background image if specified"),
    ("Carica layers DOPO setState to avoid notifiche durante il build", "Load layers AFTER setState to avoid notifications during build"),
    ("Carica l'immagine di sfondo da URL", "Load the background image from URL"),
    ("Caricamento interno: disco → file originale", "Internal loading: disk → original file"),
    ("Carica punti completi SOLO quando serve", "Load complete points ONLY when needed"),
    ("Categoria di preset per l'esportazione", "Export preset category"),
    ("Catmull-Rom splines, ma il replay non richiede la stessa precisione.", "Catmull-Rom splines, but replay doesn't require the same precision."),
    ("Centro di rotazione (default: centro selezione)", "Rotation center (default: selection center)"),
    ("Centro della viewport", "Center of the viewport"),
    ("Centro more trasparente (ink translucent)", "More transparent center (ink translucent)"),
    ("Cerchio bianco con bordo blu", "White circle with blue border"),
    ("Checkbox mantieni tratti", "Keep strokes checkbox"),
    ("Check dall'ultimo at the first (quelli sopra hanno priority)", "Check from last to first (those above have priority)"),
    ("Check se almeno un punto of the stroke is dentro il path", "Check if at least one point of the stroke is inside the path"),
    ("Check se almeno un punto of the stroke is nel path", "Check if at least one point of the stroke is in the path"),
    ("Check se ho premuto su un elemento di testo", "Check if pressed on a text element"),
    ("Check se i punti chiave della shape sono dentro il path", "Check if the key points of the shape are inside the path"),
    ("Check se QUALSIASI punto of the stroke is dentro il raggio della gomma", "Check if ANY point of the stroke is within the eraser radius"),
    ("Check allineamento con ogni altra pagina", "Check alignment with every other page"),
    ("Check il centro della shape", "Check the center of the shape"),
    ("Check if the punto is ancora dentro l'immagine", "Check if the point is still inside the image"),
    ("Checks se c'è un elemento selezionato", "Checks if there is a selected element"),
    ("Checks se ci sono selected elements", "Checks if there are selected elements"),
    ("Checks se ci sono strokes", "Checks if there are strokes"),
    ("Checks se is possible rimuovere pagine", "Checks if it is possible to remove pages"),
    ("Checks se l'ultimo pointer attivo can disegnare", "Checks if the last active pointer can draw"),
    ("Checks se questo preset richiede multi-pagina", "Checks if this preset requires multi-page"),
    ("Checks se sono i valori di default", "Checks if these are the default values"),
    ("Checks if a punto tocca questo testo", "Checks if a point touches this text"),
    ("Checks if a tile specifico is dirty", "Checks if a specific tile is dirty"),
    ("Checks if the cache copre almeno alcuni tratti", "Checks if the cache covers at least some strokes"),
    ("Checks if the cathat is valida", "Checks if the cache is valid"),
    ("Checks if the plugin nativo is available su questa piattaforma", "Checks if the native plugin is available on this platform"),
    ("Checks if the punto is dentro l'area di selezione", "Checks if the point is inside the selection area"),
    ("Checks if the registrazione ha tratti", "Checks if the recording has strokes"),
    ("Checks if the testo finisce con punteggiatura", "Checks if the text ends with punctuation"),
    ("Checks if the tratto is completamente visibile", "Checks if the stroke is completely visible"),
    ("Checks if the tratto is iniziato", "Checks if the stroke has started"),
    ("Check that the shape abbia dimensioni minime", "Check that the shape has minimum dimensions"),
    ("Chiamare ad ogni punto of the drawing per mantenere aggiornato", "Call at each point of the drawing to keep updated"),
    ("Chiamare dopo che lo stroke was aggiunto al NebulaLayerController.", "Call after the stroke was added to the NebulaLayerController."),
    ("Chiamare quando l'utente esce from the schermata o l'app va in background.", "Call when the user exits the screen or the app goes to background."),
    ("Chunk corrente per nuovi strokes", "Current chunk for new strokes"),
    ("Clear il percorso del lasso ora che gli elementi sono selezionati", "Clear the lasso path now that elements are selected"),
    ("Clear la selezione dopo l'eliminazione", "Clear the selection after deletion"),
    ("Clamp t a [0, 1] per rimanere sul segmento", "Clamp t to [0, 1] to stay on the segment"),
    ("Coefficiente di damping (0.0 = nessun damping, 1.0 = fermo subito)", "Damping coefficient (0.0 = no damping, 1.0 = stops immediately)"),
    ("Collapsabile per massimizzare canvas", "Collapsible to maximize canvas"),
    ("Colore associato al type of contenuto", "Color associated with content type"),
    ("Colore della forma", "Shape color"),
    ("Colore di sfondo diverso in mode editing", "Different background color in editing mode"),
    ("Colore di sfondo of the canvas", "Canvas background color"),
    ("Colore di sfondo", "Background color"),
    ("Colore effettivo con opacity applicata", "Effective color with applied opacity"),
    ("Colore effettivo", "Effective color"),
    ("Colore e spessore configurabili", "Configurable color and thickness"),
    ("Colore del riempimento", "Fill color"),
    ("Colore del tratto", "Stroke color"),
    ("Colori customizzabili (6 slot)", "Customizable colors (6 slots)"),
    ("Colori personalizzati per guide (null = usa default)", "Custom colors for guides (null = use default)"),
    ("Colori sfondo curati", "Curated background colors"),
    ("Color matrix 4x5 (20 elementi)", "Color matrix 4x5 (20 elements)"),
    ("Combina tutti i punti in un unico path con move/line", "Combine all points in a single path with move/line"),
    ("Combina risultati (evita duplicazione del punto di mezzo)", "Combine results (avoid midpoint duplication)"),
    ("Combina pressione e angolo", "Combine pressure and angle"),
    ("Complete il lasso e seleziona elementi", "Complete the lasso and select elements"),
    ("Complete il tratto sull'immagine", "Complete the stroke on the image"),
    ("Complete lasso e seleziona elementi", "Complete lasso and select elements"),
    ("Comprime elementData per eventi di tipo strokeAdded", "Compress elementData for strokeAdded events"),
    ("Comprime elementData per qualsiasi type of evento Time Travel", "Compress elementData for any Time Travel event type"),
    ("Comprimi elementData per stroke (delta encoding + quantizzazione + RLE)", "Compress elementData for stroke (delta encoding + quantization + RLE)"),
    ("Con culling: ~50-100 tratti renderizzati = SMOOTH", "With culling: ~50-100 rendered strokes = SMOOTH"),
    ("con doppia strategia:", "with double strategy:"),
    ("Conferma posizionamento: applica offset e aggiunge al LayerController", "Confirm placement: apply offset and add to LayerController"),
    ("Configurazione audio session iOS", "iOS audio session configuration"),
    ("Configurazione completa per l'esportazione timelapse", "Complete configuration for timelapse export"),
    ("Configurazione completa per l'esportazione", "Complete configuration for export"),
    ("Configurazione multi-current page", "Multi-page configuration"),
    ("Configurazione multi-pagina opzionale", "Optional multi-page configuration"),
    ("Configurazione multi-pagina", "Multi-page configuration"),
    ("Configurazione per l'export multi-pagina con editing interattivo", "Configuration for multi-page export with interactive editing"),
    ("entrambe le direzioni aumentano lo scale", "both directions increase the scale"),
    ("Tipi di carta organizzati per categoria", "Paper types organized by category"),
    ("Tipi di contenuto supportati per i pannelli", "Supported content types for panels"),
    ("Tipo di carta for the sfondo of the canvas", "Paper type for the canvas background"),
    ("Tipo di carta", "Paper type"),
    ("Tipo di forma corrente", "Current shape type"),
    ("Tipo di operazione background", "Background operation type"),
    ("Tipo di pennello disponibile", "Available brush type"),
    ("Tipo di registrazione", "Recording type"),
    ("Tipo di", "Type of"),
    ("Titolo della nota di origine", "Source note title"),
    ("Timestamp di fine relativo alla registrazione (millisecondi)", "End timestamp relative to the recording (milliseconds)"),
    ("Timestamp di inizio relativo alla registrazione (millisecondi)", "Start timestamp relative to the recording (milliseconds)"),
    ("Timestamp di fine relativo", "Relative end timestamp"),
    ("Timestamp di inizio relativo", "Relative start timestamp"),
    ("Timestamp ultimo accesso per ogni stroke", "Last access timestamp for each stroke"),
    ("Timestamp ultimo salvataggio", "Last save timestamp"),
    ("timestampMs cumulativo", "cumulative timestampMs"),
    ("Timestamp base:", "Base timestamp:"),
    ("Capability rilevate of the display (refresh rate, frame budget)", "Detected display capabilities (refresh rate, frame budget)"),
    ("Capability rilevate of the display", "Detected display capabilities"),
    ("Capability totale del buffer", "Total buffer capability"),
    ("Caratteristiche e rendering of the brush Biro (Ballpoint) OTTIMIZZATO", "Characteristics and rendering of the OPTIMIZED Ballpoint brush"),
    ("Carica chunk on-demand quando tile is visible", "Load chunks on-demand when tile is visible"),
    ("Canvas Ottimizzato per Test Pennelli", "Optimized Canvas for Brush Testing"),
    ("Canvas infinito: tutto is in bounds", "Infinite canvas: everything is in bounds"),
    ("CANVAS INFINITO: usa OverflowBox per disegnare oltre i limiti dello schermo", "INFINITE CANVAS: use OverflowBox to draw beyond screen limits"),
    ("CANVAS INFINITO: disegna sfondo molto grande", "INFINITE CANVAS: draw very large background"),
    ("Canvas: dimensioni dinamiche", "Canvas: dynamic dimensions"),
    ("Canvas ID corrente", "Current canvas ID"),
    ("Canvas 100k x 100k con 10.000 tratti", "Canvas 100k x 100k with 10,000 strokes"),
    ("TILE CACHING: rasterizza TUTTI i tile con contenuto", "TILE CACHING: rasterize ALL tiles with content"),
    ("Tile che devono essere ri-rasterizzati", "Tiles that need to be re-rasterized"),
    ("Coordinate del tile", "Tile coordinates"),
    ("Tilt/Orientation: 2 decimali (precisione angolare adeguata)", "Tilt/Orientation: 2 decimals (adequate angular precision)"),
    ("Inclinazione X dello stylus (-1.0 a 1.0)", "Stylus X tilt (-1.0 to 1.0)"),
    ("Inclinazione Y dello stylus (-1.0 a 1.0)", "Stylus Y tilt (-1.0 to 1.0)"),
    ("Gestire download da strokesDataUrl se mancante locale", "Handle download from strokesDataUrl if missing locally"),
    ("Tools organizzati logicamente (tipo → colore → larghezza)", "Tools organized logically (type → color → width)"),
    ("Trasforma il JSON of the stroke applicando:", "Transform the stroke JSON by applying:"),
    ("Trasformazioni canvas", "Canvas transformations"),
    ("Trasformazioni", "Transformations"),
    ("Trasla per posizionare tile all'origine", "Translate to position tile at origin"),
    ("Trasla al sistema di coordinate of the image", "Translate to the image coordinate system"),
    ("Tratto corrente in costruzione", "Current stroke in construction"),
    ("Tratto professionale completo", "Complete professional stroke"),
    ("Tratto sincronizzato con timestamps relativi alla registrazione", "Synchronized stroke with timestamps relative to the recording"),
    ("Tratti lenti → penna more \"pesante\" → tratto more spesso", 'Slow strokes → "heavier" pen → thicker stroke'),
    ("Tratti veloci → penna \"leggera\" → tratto more sottile", 'Fast strokes → "lighter" pen → thinner stroke'),
    ("Trigger rendering iniziale with the stato dell'engine", "Trigger initial rendering with the engine state"),
    ("Trova e aggiorna nella lista", "Find and update in the list"),
    ("Trova il 20% meno usato", "Find the least used 20%"),
    ("Trova la sessione a cui appartiene questo evento", "Find the session this event belongs to"),
    ("Trova l'inizio della prossima sessione", "Find the start of the next session"),
    ("L'utente vuole il pannello opaco", "The user wants the opaque panel"),
    ("True se display supporta high refresh rate (>= 90Hz)", "True if display supports high refresh rate (>= 90Hz)"),
    ("True se l'ultimo snapPoint ha effettivamente snappato", "True if the last snapPoint actually snapped"),
    ("True se questa area is per multi-page editing", "True if this area is for multi-page editing"),
    ("Undo/redo per operazioni guide", "Undo/redo for guide operations"),
    ("UN SOLO Path invece di N separate segments", "A SINGLE Path instead of N separate segments"),
    ("Update anche i bounds della selezione", "Also update the selection bounds"),
    ("Update drag - updateDrag sposta la position in canvas coordinates", "Update drag - updateDrag moves the position in canvas coordinates"),
    ("Update elemento nella lista per sincronizzare", "Update element in the list to synchronize"),
    ("Update elemento nella lista", "Update element in the list"),
    ("Update la position effettiva della pagina nel config", "Update the actual page position in the config"),
    ("Update l'elemento nella lista", "Update the element in the list"),
    ("Update position of the image selezionata", "Update position of the selected image"),
    ("Updates cache aggiungendo nuovi tratti alla cache esistente", "Updates cache by adding new strokes to the existing cache"),
    ("Updates drag dell'elemento", "Updates drag of the element"),
    ("Updates i bounds di una specific page", "Updates the bounds of a specific page"),
    ("Updates il drag (sposta elementi)", "Updates the drag (moves elements)"),
    ("Updates smart guides basandosi sui bounds degli stroke e shapes visibili", "Updates smart guides based on visible stroke and shape bounds"),
    ("Updates stato e notifica listener", "Updates state and notifies listeners"),
    ("Update stato interno", "Update internal state"),
    ("Update tutte le pagine with the nuova size mantenendo le posizioni", "Update all pages with the new size while maintaining positions"),
    ("Update UI ogni 16ms (~60fps) per animazione fluida of strokes", "Update UI every 16ms (~60fps) for smooth stroke animation"),
    ("Widget che mostra su quale pagina sta avvenendo la riproduzione", "Widget showing which page playback is occurring on"),
    ("Widget che mostra una an arrow che indica la direzione del disegno", "Widget showing an arrow indicating the drawing direction"),
    ("Widget overlay per mostrare gli elementi selezionati dal lasso (con animazione)", "Widget overlay showing elements selected by lasso (with animation)"),
    ("Widget per visualizzare il percorso del lasso durante il disegno", "Widget showing the lasso path during drawing"),
    ("willChange=true se stiamo disegnando attivamente", "willChange=true if we are actively drawing"),
    ("Ottimizzazione per animazioni", "Optimization for animations"),
    ("Calcola bounding box di TUTTO il contenuto", "Calculate bounding box of ALL content"),
    ("Sfondo solido su tutto il viewport", "Solid background on the entire viewport"),
    ("Stampa solo tile visibili", "Print only visible tiles"),
    ("Viewport-level tile rendering (~4-9 tiles visibili)", "Viewport-level tile rendering (~4-9 visible tiles)"),
    ("Rimuovi spazi multipli", "Remove multiple spaces"),
    ("Punti chiave lungo il percorso (ogni 30 punti per performance)", "Key points along the path (every 30 points for performance)"),
    ("Ritorna lista vuota (non dovrebbe mai succedere)", "Return empty list (should never happen)"),
    ("Ricostruisci stato finale", "Rebuild final state"),
    ("BACKGROUND SYNC: Se abbiamo caricato dal locale, sincronizza Firebase in background", "BACKGROUND SYNC: If loaded from local, sync Firebase in background"),
    ("Calcola larghezze con modello accumulator + nib angle", "Calculate widths with accumulator model + nib angle"),
    ("Clamp al range valido (0.1 = minimo visibile, 1.0 = massimo)", "Clamp to valid range (0.1 = minimum visible, 1.0 = maximum)"),
    ("Disegna ghost strokes con GLOW per distinguerli dai tratti originali", "Draw ghost strokes with GLOW to distinguish them from original strokes"),
    ("Disegna tutte le shape geometriche completate", "Draw all completed geometric shapes"),
    ("Disegna la shape corrente in anteprima", "Draw the current shape in preview"),
    ("Normalizza pressione per stability (clamp + smoothing)", "Normalize pressure for stability (clamp + smoothing)"),
    ("Path Builder Ottimizzato", "Optimized Path Builder"),
    ("Smoothing con ultimi 3 punti per eliminare jitter", "Smoothing with last 3 points to eliminate jitter"),
    ("Sovrapponi il nuovo stroke (con scaling HiDPI + traslazione tile)", "Overlay the new stroke (with HiDPI scaling + tile translation)"),
    ("Parte lo zoom: mantieni il focal point iniziale fisso", "Start zoom: keep the initial focal point fixed"),
    ("Salva gli elementi for the posizionamento", "Save elements for positioning"),
    ("Posiziona at the end (stato completo)", "Position at the end (complete state)"),
    ("Samsung S Pen e Apple Pencil possono essere rilevati tramite pressure", "Samsung S Pen and Apple Pencil can be detected via pressure"),
    ("Riempimento area (semi-trasparente con gradiente)", "Area fill (semi-transparent with gradient)"),
    ("Bordo principale (blu, flat) - Stile PDF Viewer", "Main border (blue, flat) - PDF Viewer style"),
    ("Bordo principale (blu, flat)", "Main border (blue, flat)"),
    ("Bordo principale (dash pattern animated)", "Main border (animated dash pattern)"),
    ("Bordo principale (animated dash pattern)", "Main border (animated dash pattern)"),
    ("Bordo interno bianco sottile", "Thin white inner border"),
    ("Bordo interno more chiaro (effetto profondità)", "Brighter inner border (depth effect)"),
    ("Bordo interno", "Inner border"),
    ("Bordo principale", "Main border"),
    
    ("Il recorder is un listener", "The recorder is a listener"),
    ("L'operazione pesante (serializzazione", "The heavy operation (serialization"),
    ("pan/zoom abilitato", "pan/zoom enabled"),
    ("stylus mode disabilitato", "stylus mode disabled"),
    ("Impostazioni pennello", "Brush settings"),
    ("Branch Explorer", "Branch Explorer"),
    ("Ultima pagina", "Last page"),
    ("Add pagina", "Add page"),
    ("Add nuovi tratti", "Add new strokes"),
    ("Add only if distanza sufficiente dall'ultimo punto", "Add only if sufficient distance from the last point"),
    ("Add path audio alle registrazioni salvate", "Add audio path to saved recordings"),
    ("Add sempre l'ultimo punto", "Always add the last point"),
    ("Adds una nuova area salvata", "Adds a new saved area"),
    ("Adds una nuova pagina alla configurazione", "Adds a new page to the configuration"),
    ("Adds una nuova pagina centrata at the point specificato (in canvas coordinates)", "Adds a new page centered at the specified point (in canvas coordinates)"),
    ("Adds un elemento immagine", "Adds an image element"),
    ("Adds un elemento testo", "Adds a text element"),
    ("Adds uno stroke alla registrazione", "Adds a stroke to the recording"),
    ("minima tra punti (ridotto da 8 per more precisione)", "minimum between points (reduced from 8 for more precision)"),
    ("Variabili per campionamento", "Sampling variables"),
    ("Varia leggermente la direzione (curva naturale)", "Slightly vary the direction (natural curve)"),
    ("Valore corrente (compatto)", "Current value (compact)"),
    ("Calculate size pagina in canvas coordinates", "Calculate page size in canvas coordinates"),
    ("Calculate speed media e direzione", "Calculate average speed and direction"),
    ("Calculate speed (modulo della derivata)", "Calculate speed (modulus of the derivative)"),
    ("Abilita/disabilita la mode stylus", "Enable/disable stylus mode"),
    ("Abilita OneEuroFilter per smoothing input", "Enable OneEuroFilter for input smoothing"),
    ("Abilita predictive rendering (ghost trail)", "Enable predictive rendering (ghost trail)"),
    ("Abilita tile caching per molti strokes", "Enable tile caching for many strokes"),
    ("Adatta il tempo di debounce based onllo stato del disegno:", "Adapt the debounce time based on the drawing state:"),
    ("Add a cache chunk corrente", "Add current cache chunk"),
    
    ("quelli sopra hanno priority", "those above have priority"),
    ("FIX #5: cache per prossima interpolazione", "FIX #5: cache for next interpolation"),
    ("TIER GATE: Solo utenti Plus/Pro sincronizzano canvas dal cloud", "TIER GATE: Only Plus/Pro users sync canvas from the cloud"),
    ("Tier corrente", "Current tier"),
    ("Tolleranza ±5Hz per account variazioni", "Tolerance ±5Hz to account for variations"),
    ("Distanza massima dal segmento (more alto = more semplificazione)", "Maximum distance from segment (higher = more simplification)"),
    ("Funzione da eseguire (es. salvataggio delta)", "Function to execute (e.g. delta saving)"),
    ("nero al 19%", "black at 19%"),
    ("nero al 25%", "black at 25%"),
    ("grigio molto tenue", "very faint gray"),
    ("no gradient", "no gradient"),
    ("null = usa default", "null = use default"),
    ("null = no gradient", "null = no gradient"),
    ("1.5x meno filtro", "1.5x less filtering"),
    ("3x meno filtro", "3x less filtering"),
    ("il replay non richiede la stessa precisione", "replay doesn't require the same precision"),
    ("inverse funzionano bene per pochi step", "inverses work well for few steps"),
    ("The soglia is conservativa: i delta", "The threshold is conservative: the delta"),
    ("The texture viene applicata come overlay semi-transparent.", "The texture is applied as a semi-transparent overlay."),
    ("The Transform widget composita il canvas layer → servono TUTTI i tile", "The Transform widget composites the canvas layer → ALL tiles are needed"),
    ("The [type] e i parametri corrispondono a quelli del `CanvasDeltaTracker`,", "The [type] and parameters correspond to those of `CanvasDeltaTracker`,"),
    ("The stylus ha valori graduali basati sulla pressione applicata", "The stylus has gradual values based on applied pressure"),
    ("Thinning: quanto la pressione influenza il raggio.", "Thinning: how much pressure influences the radius."),
    ("Aggiunti parametri realismo (jitter, inkAccumulation, smoothPath)", "Added realism parameters (jitter, inkAccumulation, smoothPath)"),
    ("WAL sempre .jsonl puro (no GZIP) per append atomico", "WAL always pure .jsonl (no GZIP) for atomic append"),
    ("WAL sempre non compresso (.jsonl puro)", "WAL always uncompressed (pure .jsonl)"),
    ("WAL sempre non compresso per performance O(1)!", "WAL always uncompressed for O(1) performance!"),
    ("prima versione taggata (attuale)", "first tagged version (current)"),
    ("prima versione taggata (feb 2026) — stessa logica di v1", "first tagged version (Feb 2026) — same logic as v1"),
    ("Encode stroke ID + createdAt per preservare identità dopo restore", "Encode stroke ID + createdAt to preserve identity after restore"),
    ("Se non specificato, assume v2 (il formato prima dell'aggiunta ID)", "If not specified, assume v2 (format before ID addition)"),
    ("strokes pre-versioning (nessun tag 'ev' nel JSON)", "strokes pre-versioning (no 'ev' tag in JSON)"),
    ("Lifecycle Management**: Flush automatico quando app va in pausa/chiude", "Lifecycle Management**: Automatic flush when app goes to pause/close"),
    ("Queue Backpressure**: Nessun delta perso, anche con scrittura veloce", "Queue Backpressure**: No lost deltas, even with fast writing"),
    ("Notifica completamento + processa queue", "Notify completion + process queue"),
    
    ("VIEWPORT CULLING: calculate current viewport", "VIEWPORT CULLING: calculate current viewport"),
    
    ("Calculate target dimensions preserving aspect ratio", "Calculate target dimensions preserving aspect ratio"),
    
    ("Current rendering engine version.", "Current rendering engine version."),
    ("Current rendering engine version", "Current rendering engine version"),
    ("Versione formato settings — incrementare quando", "Settings format version — increment when"),
    ("cambia la semantica of parameters", "parameter semantics change"),
    ("Versione async per caricamento da storage esterno", "Async version for loading from external storage"),

    ("Usato per calcolare l'intensity di disegno", "Used to calculate drawing intensity"),
    ("Usato quando paint() is chiamato solo su cambio strokes (non su pan/zoom).", "Used when paint() is called only on stroke changes (not on pan/zoom)."),
    ("usa una larghezza media per l'intero tratto.", "uses an average width for the entire stroke."),
    ("Use la distanza per calcolare variazione scala", "Use the distance to calculate scale variation"),
    ("Use la pressione per variare la larghezza?", "Use pressure to vary the width?"),
    ("Use la pressione per variare l'opacity?", "Use pressure to vary opacity?"),
    ("Use la size of thel'ultima pagina", "Use the size of the last page"),
    ("Use un singolo Paint per tutti gli strokes nel batch, riducendo overhead.", "Use a single Paint for all strokes in the batch, reducing overhead."),
    ("Use weighted average per transizioni morbide without troppi calcoli", "Use weighted average for smooth transitions without too many calculations"),
    ("Usiamo il doppio del max extent (per coprire ±maxX, ±maxY)", "We use double the max extent (to cover ±maxX, ±maxY)"),
    ("Use ultimi 2-3 punti per calcolare speed", "Use last 2-3 points to calculate speed"),
    ("Usa bounds cachato dallo stroke", "Use cached bounds from the stroke"),
    ("Usa i settings SALVATI nello stroke", "Use settings SAVED in the stroke"),
    ("non quelli globali!", "not the global ones!"),
    ("USA LA STESSA LOGICA di", "USE THE SAME LOGIC as"),
    ("Usa PaintPool per riutilizzo Paint", "Use PaintPool for Paint reuse"),
    ("Smoothing con ultimi 3 punti", "Smoothing with last 3 points"),
    ("Normalizza pressione", "Normalize pressure"),
    ("Sovrapponi il nuovo stroke", "Overlay the new stroke"),
    ("con scaling HiDPI", "with HiDPI scaling"),
    
    # Misc remaining
    ("la penna more \"pesante\"", 'the "heavier" pen'),
    ("penna \"leggera\"", '"lighter" pen'),
    ("tratto more spesso", "thicker stroke"),
    ("tratto more sottile", "thinner stroke"),
    ("toImageSync is sincrono - nessun lag!", "toImageSync is synchronous - no lag!"),
    ("Disegna ghost strokes", "Draw ghost strokes"),
    ("Disegna tutte le", "Draw all the"),
    ("Disegna tutti", "Draw all"),
    ("Disegna la", "Draw the"),
    ("disegna sfondo", "draw background"),
    ("Disegna sfondo", "Draw background"),
    ("disegna sfondo molto grande", "draw very large background"),
    ("Disegna il", "Draw the"),
    ("Disegna", "Draw"),
    
    ("Calcola larghezze", "Calculate widths"),
    ("Ricalcola", "Recalculate"),
    ("Serializza", "Serialize"),
    ("Trasforma", "Transform"),
    ("Trasla", "Translate"),
    ("Comprime", "Compress"),
    ("Comprimi", "Compress"),
    ("Cancella", "Clear"),
    ("Trova", "Find"),
    ("Cambia", "Change"),
    ("Combina", "Combine"),
    ("Compensa", "Compensate"),
    ("Conferma", "Confirm"),
    ("Verifica", "Verify"),
    ("Costruisce", "Builds"),
    ("Rimuovi", "Remove"),
    ("Rimuove", "Removes"),
    ("Restituisce", "Returns"),
    ("Restituisci", "Return"),
    ("Aggiorna", "Update"),
    ("Inizializza", "Initialize"),
    ("Configura", "Configure"),
    ("Imposta", "Set"),
    ("Calcola", "Calculate"),
    ("Visualizza", "Display"),
    ("Renderizza", "Render"),
    ("Rasterizza", "Rasterize"),
    ("Ottimizza", "Optimize"),
    ("Invalida", "Invalidate"),
    ("Carica", "Load"),
    ("Posiziona", "Position"),
    ("Sovrapponi", "Overlay"),
    ("Riempimento", "Fill"),
    ("Ricostruisci", "Rebuild"),
    ("Normalizza", "Normalize"),
    ("Abilita", "Enable"),
    ("Disabilita", "Disable"),
    ("Chiamare", "Call"),
    ("Salva", "Save"),
    
    ("Configurazione completa", "Complete configuration"),
    ("Configurazione", "Configuration"),
    ("Ottimizzazione", "Optimization"),
    ("Aggiornamento", "Update"),
    ("Trasformazioni", "Transformations"),
], key=lambda x: -len(x[0]))  # Sort longest first


def process_file(filepath):
    """Process a single file."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except (UnicodeDecodeError, FileNotFoundError):
        return False
    
    original = content
    for italian, english in PHRASES:
        if italian in content:
            content = content.replace(italian, english)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False


def find_dart_files(directories):
    dart_files = []
    for dir_path in directories:
        for root, dirs, files in os.walk(dir_path):
            for f in files:
                if f.endswith('.dart'):
                    dart_files.append(os.path.join(root, f))
    return sorted(dart_files)


def main():
    directories = [
        os.path.join(BASE, 'lib'),
        os.path.join(BASE, 'test'),
    ]
    dart_files = find_dart_files(directories)
    print(f"Found {len(dart_files)} Dart files to process")
    
    modified = 0
    for fp in dart_files:
        if process_file(fp):
            relpath = os.path.relpath(fp, BASE)
            print(f"  ✓ {relpath}")
            modified += 1
    
    print(f"\nDone! Modified {modified} files.")


if __name__ == '__main__':
    main()
