/// 📄 PDF DOCUMENT OPERATIONS — Merge, split, and page extraction.
///
/// Provides lightweight PDF manipulation without external dependencies.
/// Works with the raw byte structure of well-formed PDF 1.x files.
///
/// ```dart
/// // Merge two PDFs
/// final merged = PdfDocumentOperations.merge([pdf1Bytes, pdf2Bytes]);
///
/// // Split into individual pages
/// final pages = PdfDocumentOperations.splitByPage(pdfBytes);
///
/// // Extract specific pages
/// final subset = PdfDocumentOperations.extractPages(pdfBytes, [0, 2, 4]);
/// ```
library;

import 'dart:typed_data';
import '../../export/pdf_export_writer.dart';

/// PDF merge, split, and page extraction operations.
///
/// Uses [PdfExportWriter] internally to re-assemble valid PDF structures.
/// This approach avoids the complexity of a full PDF parser — instead,
/// it leverages the native platform provider to render pages and
/// re-exports them as new vector PDFs.
///
/// For byte-level merge/split of arbitrary PDFs (preserving fonts, images,
/// etc.), a full PDF object parser would be needed. This implementation
/// focuses on Nebula Engine's own exported PDFs (well-formed PDF 1.4).
class PdfDocumentOperations {
  PdfDocumentOperations._();

  // ---------------------------------------------------------------------------
  // Merge
  // ---------------------------------------------------------------------------

  /// Merge multiple PDF byte arrays into a single multi-page PDF.
  ///
  /// Each input PDF's pages are appended sequentially.
  /// Supports PDFs generated by [PdfExportWriter] or any well-formed PDF 1.4.
  ///
  /// Returns the merged PDF bytes, or an empty [Uint8List] if inputs are empty.
  static Uint8List merge(List<Uint8List> documents, {String? title}) {
    if (documents.isEmpty) return Uint8List(0);
    if (documents.length == 1) return documents.first;

    final pages = <_ParsedPage>[];
    for (final doc in documents) {
      pages.addAll(_parsePages(doc));
    }

    if (pages.isEmpty) return Uint8List(0);

    return _rebuildPdf(pages, title: title ?? 'Merged Document');
  }

  // ---------------------------------------------------------------------------
  // Split
  // ---------------------------------------------------------------------------

  /// Split a PDF into individual single-page PDFs.
  ///
  /// Returns a list of PDF byte arrays, one per page.
  static List<Uint8List> splitByPage(Uint8List document) {
    final pages = _parsePages(document);
    if (pages.isEmpty) return [];

    return pages.map((p) => _rebuildPdf([p])).toList();
  }

  /// Extract specific pages from a PDF by their zero-based indices.
  ///
  /// Pages not present in the document are silently skipped.
  static Uint8List extractPages(
    Uint8List document,
    List<int> pageIndices, {
    String? title,
  }) {
    final pages = _parsePages(document);
    if (pages.isEmpty) return Uint8List(0);

    final selected = <_ParsedPage>[];
    for (final idx in pageIndices) {
      if (idx >= 0 && idx < pages.length) {
        selected.add(pages[idx]);
      }
    }

    if (selected.isEmpty) return Uint8List(0);
    return _rebuildPdf(selected, title: title);
  }

  // ---------------------------------------------------------------------------
  // Page count
  // ---------------------------------------------------------------------------

  /// Get the number of pages in a PDF without fully parsing it.
  static int pageCount(Uint8List document) {
    return _parsePages(document).length;
  }

  // ---------------------------------------------------------------------------
  // Internal PDF parsing
  // ---------------------------------------------------------------------------

  /// Parse a PDF and extract individual page content streams.
  ///
  /// This is a lightweight parser that handles well-formed PDF 1.x files.
  /// It finds page objects, extracts their MediaBox and content streams.
  static List<_ParsedPage> _parsePages(Uint8List bytes) {
    final pages = <_ParsedPage>[];

    try {
      final text = String.fromCharCodes(bytes);

      // Find all page objects with MediaBox.
      // We look for "/Type /Page" (not "/Type /Pages") objects.
      final pagePattern = RegExp(
        r'(\d+)\s+0\s+obj[^]*?/Type\s+/Page\b(?!\s*s)[^]*?endobj',
      );

      for (final match in pagePattern.allMatches(text)) {
        final pageObj = match.group(0) ?? '';

        // Extract MediaBox.
        final mediaBoxMatch = RegExp(
          r'/MediaBox\s*\[\s*(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)\s+'
          r'(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)\s*\]',
        ).firstMatch(pageObj);

        if (mediaBoxMatch == null) continue;

        final width = double.tryParse(mediaBoxMatch.group(3) ?? '') ?? 595;
        final height = double.tryParse(mediaBoxMatch.group(4) ?? '') ?? 842;

        // Extract content stream reference.
        final contentsMatch = RegExp(
          r'/Contents\s+(\d+)\s+0\s+R',
        ).firstMatch(pageObj);

        String contentStream = '';
        if (contentsMatch != null) {
          final streamId = contentsMatch.group(1);
          // Find the stream object.
          final streamPattern = RegExp(
            '$streamId\\s+0\\s+obj[^]*?stream\\r?\\n([^]*?)\\r?\\nendstream',
          );
          final streamMatch = streamPattern.firstMatch(text);
          if (streamMatch != null) {
            contentStream = streamMatch.group(1) ?? '';
          }
        }

        pages.add(
          _ParsedPage(
            width: width,
            height: height,
            contentStream: contentStream,
          ),
        );
      }
    } catch (_) {
      // If parsing fails, return empty list.
    }

    return pages;
  }

  /// Rebuild a valid PDF from parsed pages using PdfExportWriter.
  static Uint8List _rebuildPdf(List<_ParsedPage> pages, {String? title}) {
    final writer = PdfExportWriter(enableCompression: false);

    for (final page in pages) {
      writer.beginPage(width: page.width, height: page.height);
      // Inject raw content stream operators.
      if (page.contentStream.isNotEmpty) {
        writer.injectRawContent(page.contentStream);
      }
    }

    return writer.finish(title: title);
  }
}

/// A parsed PDF page with its dimensions and content stream.
class _ParsedPage {
  final double width;
  final double height;
  final String contentStream;

  const _ParsedPage({
    required this.width,
    required this.height,
    required this.contentStream,
  });
}
