/// Content origin taxonomy — tracks how content was created (A20.3).
///
/// Each node on the canvas has a provenance tag indicating whether it was:
/// - **handwritten** by the student (🟢 green)
/// - **imported** from external sources (🔵 blue)
/// - **aiGenerated** by Fluera's AI engine (🔴 red)
///
/// This taxonomy enables the engine to:
/// 1. Weight retrieval practice differently (handwritten > imported > AI)
/// 2. Show visual provenance indicators in the UI
/// 3. Track student autonomy metrics over time
enum ContentOrigin {
  /// Created by the student's own hand (handwriting, drawing, manual text).
  /// Visual indicator: 🟢 green dot.
  handwriting,

  /// Imported from external sources (PDF, image, pasted text, camera).
  /// Visual indicator: 🔵 blue dot.
  imported,

  /// Generated by Fluera's AI engine (Socratic answers, Ghost Map fills, etc.).
  /// Visual indicator: 🔴 red dot.
  aiGenerated,
}

/// Visual constants for content origin indicators.
abstract final class ContentOriginColors {
  /// 🟢 Handwriting — student-authored content.
  static const int handwritingLight = 0xFF4CAF50;
  static const int handwritingDark = 0xFF66BB6A;

  /// 🔵 Imported — external content.
  static const int importedLight = 0xFF2196F3;
  static const int importedDark = 0xFF42A5F5;

  /// 🔴 AI-generated — machine-authored content.
  static const int aiGeneratedLight = 0xFFE53935;
  static const int aiGeneratedDark = 0xFFEF5350;

  /// Size of the origin dot indicator (in logical pixels, scale-independent).
  static const double dotRadius = 3.0;

  /// Offset from the top-right corner of the node bounds.
  static const double dotOffsetX = -6.0;
  static const double dotOffsetY = 6.0;

  /// Opacity of the dot indicator.
  static const double dotOpacity = 0.7;
}
