/// 🧠 FSRS — Free Spaced Repetition Scheduler.
///
/// Implements the FSRS algorithm as specified in Appendix A5 of the
/// specifica implementativa. Uses stability/difficulty model instead of
/// SM-2's easiness factor.
///
/// Cognitive science foundations:
///   - **FSRS** (Free Spaced Repetition Scheduler): Modern, open-source
///     algorithm modelling stability (memory duration) and difficulty
///     (intrinsic concept complexity) separately.
///   - **Hypercorrection Effect** (Butterfield & Metcalfe, 2001):
///     high-confidence errors create stronger memory traces.
///   - **Desirable Difficulties** (Bjork, 1994):
///     effortful retrieval strengthens long-term retention.
///
/// No Flutter dependencies — testable in isolation.
library;

import 'dart:math';

// ─────────────────────────────────────────────────────────────────────────────
// FSRS Card State Machine
// ─────────────────────────────────────────────────────────────────────────────

/// The 4 states in the FSRS state machine.
///
/// Spec A5.2: `"state": "new|learning|review|relearning"`
enum FsrsState {
  /// Brand new card, never reviewed.
  newCard,

  /// In the initial learning phase (short intervals).
  learning,

  /// Successfully graduated to review phase (long intervals).
  review,

  /// Previously known but lapsed — re-learning with short intervals.
  relearning,
}

// ─────────────────────────────────────────────────────────────────────────────
// FSRS Card Data Model
// ─────────────────────────────────────────────────────────────────────────────

/// Immutable snapshot of a concept's spaced repetition state.
///
/// Spec A5.2: Each node maintains stability, difficulty, elapsed/scheduled
/// days, reps, lapses, state, stage, and review timestamps.
class SrsCardData {
  /// Memory stability: days after which recall probability drops to 90%.
  /// Range: [0.1, ∞). Higher = more durable memory.
  final double stability;

  /// Intrinsic difficulty of the concept.
  /// Range: [0.0, 1.0]. Higher = harder to learn.
  final double difficulty;

  /// Days elapsed since last review.
  final int elapsedDays;

  /// Scheduled interval from last review to next review (days).
  final int scheduledDays;

  /// Number of consecutive successful reviews.
  final int reps;

  /// Total number of times the student forgot this concept.
  final int lapses;

  /// Current state in the FSRS state machine.
  final FsrsState state;

  /// When the next review is due.
  final DateTime nextReview;

  /// When the last review occurred.
  final DateTime lastReview;

  /// Desired retention rate (0.80–0.97). Default: 0.90.
  /// Spec A5.5: configurable by student.
  final double desiredRetention;

  /// Recent review results for Stage 4/5 lapse check.
  /// Stores the last N review outcomes: true = correct, false = lapse.
  /// Spec A5.7: Stage 4 requires "lapses = 0 negli ultimi 3 reps",
  /// Stage 5 requires "lapses = 0 negli ultimi 5 reps".
  final List<bool> recentResults;

  const SrsCardData({
    required this.stability,
    required this.difficulty,
    required this.elapsedDays,
    required this.scheduledDays,
    required this.reps,
    required this.lapses,
    required this.state,
    required this.nextReview,
    required this.lastReview,
    this.desiredRetention = 0.90,
    this.recentResults = const [],
  });

  /// Brand-new card with no review history.
  ///
  /// Initial stability = 1.0 day (will be reviewed tomorrow).
  /// Initial difficulty = 0.5 (neutral).
  factory SrsCardData.newCard() {
    final now = DateTime.now();
    return SrsCardData(
      stability: 1.0,
      difficulty: 0.5,
      elapsedDays: 0,
      scheduledDays: 1,
      reps: 0,
      lapses: 0,
      state: FsrsState.newCard,
      nextReview: now.add(const Duration(days: 1)),
      lastReview: now,
    );
  }

  /// Card for a concept discovered via Ghost Map.
  ///
  /// Spec A5.4: "Nodo scoperto in Ghost Map — initial_stability = 0.5"
  /// The concept wasn't generated by the student, so recall will be weaker.
  factory SrsCardData.fromGhostMap() {
    final now = DateTime.now();
    return SrsCardData(
      stability: 0.5,
      difficulty: 0.6, // Slightly harder — not self-generated
      elapsedDays: 0,
      scheduledDays: 1,
      reps: 0,
      lapses: 0,
      state: FsrsState.newCard,
      nextReview: now.add(const Duration(days: 1)),
      lastReview: now,
    );
  }

  /// Create from the old legacy format (just a DateTime).
  factory SrsCardData.fromLegacyDateTime(DateTime nextReviewDate) {
    final now = DateTime.now();
    final daysUntil = nextReviewDate.difference(now).inHours / 24.0;
    return SrsCardData(
      stability: max(0.1, daysUntil),
      difficulty: 0.5,
      elapsedDays: 0,
      scheduledDays: max(1, daysUntil.round()),
      reps: 1,
      lapses: 0,
      state: FsrsState.review,
      nextReview: nextReviewDate,
      lastReview: now,
    );
  }

  /// Migrate from old SM-2 format to FSRS.
  ///
  /// Maps SM-2 parameters to FSRS equivalents:
  ///   - easiness (1.3–3.0) → difficulty (1.0–0.0), inverted scale
  ///   - interval → stability (approximate)
  ///   - repetitions → reps
  ///   - lapses → lapses (direct)
  factory SrsCardData.migrateFromSm2({
    required int repetitions,
    required double easiness,
    required double interval,
    required DateTime nextReview,
    required DateTime lastReview,
    int lapses = 0,
  }) {
    // Map easiness [1.3, 3.0] → difficulty [1.0, 0.0] (inverted)
    final difficulty = (1.0 - (easiness - 1.3) / 1.7).clamp(0.0, 1.0);

    // SM-2 interval approximates FSRS stability
    final stability = max(0.1, interval);

    // Determine state based on SM-2 repetitions
    final FsrsState state;
    if (repetitions == 0) {
      state = lapses > 0 ? FsrsState.relearning : FsrsState.newCard;
    } else if (repetitions <= 2) {
      state = FsrsState.learning;
    } else {
      state = FsrsState.review;
    }

    return SrsCardData(
      stability: stability,
      difficulty: difficulty,
      elapsedDays: DateTime.now().difference(lastReview).inDays,
      scheduledDays: max(1, interval.round()),
      reps: repetitions,
      lapses: lapses,
      state: state,
      nextReview: nextReview,
      lastReview: lastReview,
    );
  }

  /// Returns a copy with only the specified fields replaced.
  SrsCardData copyWith({
    double? stability,
    double? difficulty,
    int? elapsedDays,
    int? scheduledDays,
    int? reps,
    int? lapses,
    FsrsState? state,
    DateTime? nextReview,
    DateTime? lastReview,
    double? desiredRetention,
    List<bool>? recentResults,
  }) {
    return SrsCardData(
      stability: stability ?? this.stability,
      difficulty: difficulty ?? this.difficulty,
      elapsedDays: elapsedDays ?? this.elapsedDays,
      scheduledDays: scheduledDays ?? this.scheduledDays,
      reps: reps ?? this.reps,
      lapses: lapses ?? this.lapses,
      state: state ?? this.state,
      nextReview: nextReview ?? this.nextReview,
      lastReview: lastReview ?? this.lastReview,
      desiredRetention: desiredRetention ?? this.desiredRetention,
      recentResults: recentResults ?? this.recentResults,
    );
  }

  bool get isDue => DateTime.now().isAfter(nextReview);

  /// Current retrievability — probability of recall at this moment.
  /// R = e^(-elapsed_days / stability)
  /// When elapsed_days = stability, R ≈ 0.37 (not 0.9 — that's by design,
  /// the next review is scheduled at the point where R = desired_retention).
  double get retrievability {
    if (stability <= 0.0) return 0.0;
    return exp(-elapsedDays / stability);
  }

  /// Whether the last N reviews had zero lapses.
  /// Used for Stage 4 (last 3) and Stage 5 (last 5) qualification.
  bool hasNoRecentLapses(int n) {
    if (recentResults.length < n) return false;
    final recent = recentResults.length > n
        ? recentResults.sublist(recentResults.length - n)
        : recentResults;
    return recent.every((r) => r); // all correct = no lapses
  }

  Map<String, dynamic> toJson() => {
        'stability': stability,
        'difficulty': difficulty,
        'elapsedDays': elapsedDays,
        'scheduledDays': scheduledDays,
        'reps': reps,
        'lapses': lapses,
        'state': state.index,
        'nextReview': nextReview.millisecondsSinceEpoch,
        'lastReview': lastReview.millisecondsSinceEpoch,
        'desiredRetention': desiredRetention,
        'recentResults': recentResults.map((r) => r ? 1 : 0).toList(),
        // Format version marker for future migrations
        'v': 2,
      };

  factory SrsCardData.fromJson(Map<String, dynamic> j) {
    // Detect format version
    final version = (j['v'] as num?)?.toInt() ?? 1;
    if (version == 1) {
      // Legacy SM-2 format — migrate on read
      return SrsCardData.migrateFromSm2(
        repetitions: (j['repetitions'] as num?)?.toInt() ?? 0,
        easiness: (j['easiness'] as num?)?.toDouble() ?? 2.5,
        interval: (j['interval'] as num?)?.toDouble() ?? 0,
        nextReview: DateTime.fromMillisecondsSinceEpoch(
          (j['nextReview'] as num?)?.toInt() ??
              DateTime.now().millisecondsSinceEpoch,
        ),
        lastReview: DateTime.fromMillisecondsSinceEpoch(
          (j['lastReview'] as num?)?.toInt() ??
              DateTime.now().millisecondsSinceEpoch,
        ),
        lapses: (j['lapses'] as num?)?.toInt() ?? 0,
      );
    }

    // Version 2: native FSRS format
    final recentRaw = (j['recentResults'] as List<dynamic>?) ?? [];
    return SrsCardData(
      stability: (j['stability'] as num?)?.toDouble() ?? 1.0,
      difficulty: (j['difficulty'] as num?)?.toDouble() ?? 0.5,
      elapsedDays: (j['elapsedDays'] as num?)?.toInt() ?? 0,
      scheduledDays: (j['scheduledDays'] as num?)?.toInt() ?? 1,
      reps: (j['reps'] as num?)?.toInt() ?? 0,
      lapses: (j['lapses'] as num?)?.toInt() ?? 0,
      state: FsrsState.values[
          ((j['state'] as num?)?.toInt() ?? 0).clamp(0, FsrsState.values.length - 1)],
      nextReview: DateTime.fromMillisecondsSinceEpoch(
        (j['nextReview'] as num?)?.toInt() ??
            DateTime.now().millisecondsSinceEpoch,
      ),
      lastReview: DateTime.fromMillisecondsSinceEpoch(
        (j['lastReview'] as num?)?.toInt() ??
            DateTime.now().millisecondsSinceEpoch,
      ),
      desiredRetention: (j['desiredRetention'] as num?)?.toDouble() ?? 0.90,
      recentResults: recentRaw.map((e) => (e as num).toInt() == 1).toList(),
    );
  }

  @override
  String toString() =>
      'SrsCard(S=${stability.toStringAsFixed(1)}, D=${difficulty.toStringAsFixed(2)}, '
      'reps=$reps, lapses=$lapses, state=${state.name}, '
      'scheduled=${scheduledDays}d)';
}

// ─────────────────────────────────────────────────────────────────────────────
// FSRS Modifiers — Fluera-specific pedagogical adjustments
// ─────────────────────────────────────────────────────────────────────────────

/// Pedagogical modifiers collected during the review session.
///
/// Spec A5.4: These adjust stability AFTER the base FSRS calculation.
/// Order: FSRS base → apply modifiers → clamp to floor/ceiling (A5-02).
class FsrsModifiers {
  /// Whether the student peeked at the answer (Passo 2).
  /// Malus: stability ×0.8
  final bool peeked;

  /// Number of hints/breadcrumbs used (Passo 3).
  /// Malus: stability ×0.85^hintsUsed
  final int hintsUsed;

  /// Whether the student had to zoom in to read (Passo 6).
  /// Malus: stability ×0.9
  final bool zoomedIn;

  /// Response time in seconds.
  /// <5s → Bonus ×1.1 (automatic retrieval)
  /// >15s → Malus ×0.9 (effortful retrieval)
  final double? responseTimeSec;

  /// Whether this concept was discovered via Ghost Map (Passo 4).
  /// The initial_stability is set in SrsCardData.fromGhostMap(), but
  /// this flag enables the hypercorrection bonus tracking.
  final bool fromGhostMap;

  /// Confidence level (1–5) from the metacognitive slider.
  /// Used for hypercorrection effect on failures.
  final int confidence;

  const FsrsModifiers({
    this.peeked = false,
    this.hintsUsed = 0,
    this.zoomedIn = false,
    this.responseTimeSec,
    this.fromGhostMap = false,
    this.confidence = 0,
  });

  /// No modifiers — clean review.
  static const none = FsrsModifiers();

  /// Calculate the cumulative stability multiplier.
  ///
  /// Returns a multiplier ∈ (0, 2] that is applied post-FSRS to the
  /// new stability value. All modifiers are multiplicative.
  double computeMultiplier({required bool wasCorrect}) {
    double mult = 1.0;

    // ── Peek malus ──
    if (peeked) {
      mult *= 0.8;
    }

    // ── Breadcrumb malus (cumulative per hint) ──
    if (hintsUsed > 0) {
      mult *= pow(0.85, min(hintsUsed, 5)).toDouble();
    }

    // ── Zoom-in malus ──
    if (zoomedIn) {
      mult *= 0.9;
    }

    // ── Response time bonus/malus ──
    if (responseTimeSec != null) {
      if (responseTimeSec! < 5.0 && wasCorrect) {
        mult *= 1.1; // Fast + correct = automatic retrieval
      } else if (responseTimeSec! > 15.0) {
        mult *= 0.9; // Slow = fragile retrieval
      }
    }

    // ── Hypercorrection bonus (Butterfield & Metcalfe, 2001) ──
    // High confidence + incorrect → stronger memory trace from shock
    if (!wasCorrect && confidence >= 4) {
      mult *= 1.3;
    }

    return mult.clamp(0.3, 2.0);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// FSRS Default Weights
// ─────────────────────────────────────────────────────────────────────────────

/// Default FSRS weights from spec A5.3.
///
/// These can be personalized per-student after 100+ reviews (A5-06)
/// via gradient descent on real review data.
class FsrsWeights {
  /// w[0]: Base growth factor for stability after correct recall.
  final double w0;

  /// w[1]: Impact of difficulty on stability growth.
  final double w1;

  /// w[2]: Impact of current stability on growth.
  final double w2;

  /// w[3]: Impact of retrievability on growth.
  final double w3;

  /// w[4]: Base decay factor after lapse.
  final double w4;

  /// w[5]: Impact of difficulty on decay after lapse.
  final double w5;

  /// w[6]: Impact of stability on decay after lapse.
  final double w6;

  /// w[7]: Impact of retrievability on decay after lapse.
  final double w7;

  const FsrsWeights({
    this.w0 = 0.40,
    this.w1 = 0.60,
    this.w2 = 2.40,
    this.w3 = 0.10,
    this.w4 = 5.00,
    this.w5 = 0.10,
    this.w6 = 0.80,
    this.w7 = 0.20,
  });

  /// Default weights from spec A5.3.
  static const defaults = FsrsWeights();

  Map<String, double> toJson() => {
        'w0': w0, 'w1': w1, 'w2': w2, 'w3': w3,
        'w4': w4, 'w5': w5, 'w6': w6, 'w7': w7,
      };

  factory FsrsWeights.fromJson(Map<String, dynamic> j) => FsrsWeights(
        w0: (j['w0'] as num?)?.toDouble() ?? 0.40,
        w1: (j['w1'] as num?)?.toDouble() ?? 0.60,
        w2: (j['w2'] as num?)?.toDouble() ?? 2.40,
        w3: (j['w3'] as num?)?.toDouble() ?? 0.10,
        w4: (j['w4'] as num?)?.toDouble() ?? 5.00,
        w5: (j['w5'] as num?)?.toDouble() ?? 0.10,
        w6: (j['w6'] as num?)?.toDouble() ?? 0.80,
        w7: (j['w7'] as num?)?.toDouble() ?? 0.20,
      );
}

// ─────────────────────────────────────────────────────────────────────────────
// FSRS Scheduler
// ─────────────────────────────────────────────────────────────────────────────

/// Pure-logic FSRS scheduler implementing spec A5.3.
///
/// The scheduling pipeline for each review:
///   1. Calculate retrievability R at review time
///   2. Apply FSRS formula to compute new stability
///   3. Apply Fluera modifiers (A5.4)
///   4. Clamp to floor/ceiling (A5.5)
///   5. Compute next review date from stability + desired_retention
///   6. Update difficulty based on performance
///   7. Record result in recentResults history
class FsrsScheduler {
  const FsrsScheduler._();

  // ── Floor/Ceiling constants (A5.5) ──

  /// Minimum interval: no concept is reviewed more than once per day.
  static const double _minIntervalDays = 1.0;

  /// Maximum interval: even Integrated nodes return at least yearly.
  static const double _maxIntervalDays = 365.0;

  /// Minimum stability: prevents degenerate scheduling.
  static const double _minStability = 0.1;

  /// Reviews a card and returns the updated state.
  ///
  /// [quality]: 0 = incorrect/skipped, 1 = partial, 2 = correct.
  /// [modifiers]: Fluera-specific pedagogical adjustments (A5.4).
  /// [weights]: FSRS weights (default or student-personalized after 100+ reviews).
  ///
  /// Pipeline: A5-02 specifies the order:
  ///   FSRS base → apply modifiers → clamp floor/ceiling
  static SrsCardData review(
    SrsCardData card, {
    required int quality,
    int confidence = 0,
    FsrsModifiers modifiers = FsrsModifiers.none,
    FsrsWeights weights = FsrsWeights.defaults,
  }) {
    final now = DateTime.now();
    final wasCorrect = quality >= 2;
    final wasPartial = quality == 1;
    final R = card.retrievability;

    // ── Step 1: Calculate new stability via FSRS formula (A5.3) ─────────

    double newStability;
    double newDifficulty = card.difficulty;
    FsrsState newState;
    int newLapses = card.lapses;
    int newReps = card.reps;

    if (wasCorrect) {
      // ── CORRECT RECALL ────────────────────────────────────────────────
      // new_stability = S * (1 + e^(w[0]) * D^(-w[1]) * (S^w[2] - 1) * e^(w[3] * (1 - R)))
      final growthFactor = exp(weights.w0) *
          pow(card.difficulty.clamp(0.01, 1.0), -weights.w1) *
          (pow(card.stability.clamp(_minStability, 10000.0), weights.w2) - 1) *
          exp(weights.w3 * (1 - R));
      newStability = card.stability * (1 + growthFactor);

      newReps = card.reps + 1;
      newState = FsrsState.review;

      // Decrease difficulty slightly on correct recall
      newDifficulty = (card.difficulty - 0.05).clamp(0.0, 1.0);
    } else if (wasPartial) {
      // ── PARTIAL RECALL ────────────────────────────────────────────────
      // Treat as a weak correct: stability grows but less
      final growthFactor = exp(weights.w0) *
          pow(card.difficulty.clamp(0.01, 1.0), -weights.w1) *
          (pow(card.stability.clamp(_minStability, 10000.0), weights.w2) - 1) *
          exp(weights.w3 * (1 - R));
      newStability = card.stability * (1 + growthFactor * 0.5);

      // Don't increment reps for partial recall
      newState = card.state == FsrsState.newCard
          ? FsrsState.learning
          : card.state;

      // Difficulty unchanged on partial
    } else {
      // ── INCORRECT RECALL (LAPSE) ──────────────────────────────────────
      // new_stability = w[4] * D^(-w[5]) * (S^w[6] + 1) * e^(w[7] * (1 - R))
      newStability = weights.w4 *
          pow(card.difficulty.clamp(0.01, 1.0), -weights.w5) *
          (pow(card.stability.clamp(_minStability, 10000.0), weights.w6) + 1) *
          exp(weights.w7 * (1 - R));

      newReps = 0;
      newLapses = card.lapses + 1;
      newState = card.state == FsrsState.newCard
          ? FsrsState.learning
          : FsrsState.relearning;

      // Increase difficulty on lapse
      newDifficulty = (card.difficulty + 0.1).clamp(0.0, 1.0);
    }

    // ── Step 2: Apply Fluera modifiers (A5.4) ───────────────────────────
    final modifier = modifiers.computeMultiplier(wasCorrect: wasCorrect);
    newStability *= modifier;

    // ── Step 3: Clamp to floor/ceiling (A5.5) ───────────────────────────
    newStability = newStability.clamp(_minStability, double.infinity);

    // ── Step 4: Compute next interval from stability + retention ────────
    // new_interval = new_stability * ln(desired_retention) / ln(0.9)
    final dr = card.desiredRetention.clamp(0.80, 0.97);
    double newInterval;
    if (wasCorrect || wasPartial) {
      newInterval = newStability * log(dr) / log(0.9);
    } else {
      // After lapse: use stability directly as interval
      newInterval = max(_minIntervalDays, newStability);
    }

    // Clamp interval to [1, 365] days
    newInterval = newInterval.clamp(_minIntervalDays, _maxIntervalDays);

    // ── Step 5: Update recent results history ───────────────────────────
    // Keep last 10 results for Stage 4/5 lapse checking
    final updatedResults = List<bool>.from(card.recentResults);
    updatedResults.add(wasCorrect);
    if (updatedResults.length > 10) {
      updatedResults.removeRange(0, updatedResults.length - 10);
    }

    return SrsCardData(
      stability: newStability,
      difficulty: newDifficulty,
      elapsedDays: 0, // Reset: just reviewed
      scheduledDays: newInterval.round(),
      reps: newReps,
      lapses: newLapses,
      state: newState,
      nextReview: now.add(Duration(hours: (newInterval * 24).round())),
      lastReview: now,
      desiredRetention: card.desiredRetention,
      recentResults: updatedResults,
    );
  }

  /// Converts a legacy `Map<String, int>` (concept → epoch ms) schedule
  /// to the new `Map<String, SrsCardData>` format.
  ///
  /// Handles three formats:
  ///   1. New FSRS v2 format (Map with 'v': 2)
  ///   2. Old SM-2 format (Map with 'repetitions'/'easiness')
  ///   3. Legacy epoch format (int milliseconds since epoch)
  static Map<String, SrsCardData> migrateLegacySchedule(
    Map<String, dynamic> legacyMap,
  ) {
    final result = <String, SrsCardData>{};
    for (final entry in legacyMap.entries) {
      final value = entry.value;
      if (value is Map<String, dynamic>) {
        // fromJson handles both v1 (SM-2) and v2 (FSRS) via version check
        result[entry.key] = SrsCardData.fromJson(value);
      } else if (value is int) {
        // Legacy: milliseconds since epoch
        result[entry.key] = SrsCardData.fromLegacyDateTime(
          DateTime.fromMillisecondsSinceEpoch(value),
        );
      }
    }
    return result;
  }

  /// Calculates the urgency score for a node, used for session prioritization.
  ///
  /// Spec A5.6: urgency = overdue_days / scheduled_days
  /// With bonuses for hypercorrection history and ghost map origin.
  static double urgencyScore(
    SrsCardData card, {
    bool isHypercorrection = false,
    bool fromGhostMap = false,
  }) {
    final now = DateTime.now();
    final overdueDays = now.difference(card.nextReview).inHours / 24.0;
    if (overdueDays <= 0) return 0.0; // Not yet due

    final scheduled = card.scheduledDays.clamp(1, 365);
    double urgency = overdueDays / scheduled;

    // Priority bonuses from A5.6
    if (isHypercorrection) urgency *= 1.3;
    if (fromGhostMap) urgency *= 1.5;

    return urgency;
  }
}
